### ISSUE TITLE
同时设置 DNS 和国内 DNS 后，部分域名无法解析

### ISSUE THREAD

**Issue by xnfa** [immortalwrt/homeproxy#103]
同时设置 DNS 和国内 DNS 后，dig login.live.com，返回如下
`;; Truncated, retrying in TCP mode. ;; communications error to 192.168.1.1#53: end of file`
如果禁用国内 DNS 则正常。看了下正常的解析结果，怀疑是返回记录太大了？

DNS 服务器
1.1.1.1
国内 DNS 服务器
223.5.5.5

### Actual behaviour
;; Truncated, retrying in TCP mode.
;; communications error to 192.168.1.1#53: end of file

### Expected behaviour
; <<>> DiG 9.10.6 <<>> login.live.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 54487
;; flags: qr rd ra; QUERY: 1, ANSWER: 12, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;login.live.com. IN A

;; ANSWER SECTION:
login.live.com. 3598 IN CNAME login.msa.msidentity.com.
login.msa.msidentity.com. 3598 IN CNAME [www.tm.lg.prod.aadmsa.trafficmanager.net](http://www.tm.lg.prod.aadmsa.trafficmanager.net/).
[www.tm.lg.prod.aadmsa.trafficmanager.net](http://www.tm.lg.prod.aadmsa.trafficmanager.net/). 3598 IN CNAME prdv4a.aadg.msidentity.com.
prdv4a.aadg.msidentity.com. 3598 IN CNAME [www.tm.v4.a.prd.aadg.trafficmanager.net](http://www.tm.v4.a.prd.aadg.trafficmanager.net/).
[www.tm.v4.a.prd.aadg.trafficmanager.net](http://www.tm.v4.a.prd.aadg.trafficmanager.net/). 3598 IN A 40.126.35.21
[www.tm.v4.a.prd.aadg.trafficmanager.net](http://www.tm.v4.a.prd.aadg.trafficmanager.net/). 3598 IN A 20.190.163.21
[www.tm.v4.a.prd.aadg.trafficmanager.net](http://www.tm.v4.a.prd.aadg.trafficmanager.net/). 3598 IN A 40.126.35.145
[www.tm.v4.a.prd.aadg.trafficmanager.net](http://www.tm.v4.a.prd.aadg.trafficmanager.net/). 3598 IN A 40.126.35.134
[www.tm.v4.a.prd.aadg.trafficmanager.net](http://www.tm.v4.a.prd.aadg.trafficmanager.net/). 3598 IN A 20.190.163.20
[www.tm.v4.a.prd.aadg.trafficmanager.net](http://www.tm.v4.a.prd.aadg.trafficmanager.net/). 3598 IN A 40.126.35.150
[www.tm.v4.a.prd.aadg.trafficmanager.net](http://www.tm.v4.a.prd.aadg.trafficmanager.net/). 3598 IN A 40.126.35.144
[www.tm.v4.a.prd.aadg.trafficmanager.net](http://www.tm.v4.a.prd.aadg.trafficmanager.net/). 3598 IN A 40.126.35.80

;; Query time: 2 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Wed May 22 23:47:49 CST 2024
;; MSG SIZE rcvd: 356

**Comment by 1715173329** [comment]
使用新版 chinadns-ng 可以改善此情况，但是目前打包比较麻烦，~~还在摸鱼~~。
