### ISSUE TITLE
how to use shawdsocksR?

### ISSUE THREAD

**Issue by jack338c** [immortalwrt/homeproxy#113]
hello Master
I use ssr share link like ssr://MTk3LnVzMm4udG9wOjMxMD*******.but it show up "No valid share link found."
then I tried add ssr node.but did't find any options for shawdsocksR node
please help me
thanks for your hard work on this program
![Screenshot 2024-06-29 at 09 03 37](https://github.com/immortalwrt/homeproxy/assets/10782586/e335f359-8b3e-46f8-ac13-aef4d7a6a0c4)
![Screenshot 2024-06-29 at 08 52 41](https://github.com/immortalwrt/homeproxy/assets/10782586/343f21a8-04cb-4239-85ad-af282f477233)

**Comment by muink** [comment]
ssr is deprecated in sing-box.

**Comment by jack338c** [comment]
> ssr is deprecated in sing-box.

understood,thank you
