### ISSUE TITLE
无法翻墙 显示 too many open streams

### ISSUE THREAD

**Issue by daydaya** [immortalwrt/homeproxy#117]
运行一段时间之后，会无法翻墙，后台点连接检查，Google是正常的，但是实际上其他连接了的客户端无法访问

## 后台设置
节点为：hysteria2 协议
路由模式为：大陆白名单
路由端口：仅常用端口
代理模式为：redirect TCP + Tproxy UDP
ipv6支持：关闭
openwrt 本身是开启了ipv6的，因为电视需要观看ipv6的直播源，是不是ipv6问题多？之前用 openclash 开启 ipv6 也总是出问题

## sing-box 客户端 日志
+0000 2024-07-07 10:31:44 ERROR dns: exchange failed for developer.themoviedb.org. IN A: too many open streams
+0000 2024-07-07 10:31:49 ERROR [2181821438 38ms] inbound/redirect[redirect-in]: process connection from 192.168.2.2:56198: too many open streams
+0000 2024-07-07 10:31:49 ERROR [2620976758 38ms] inbound/redirect[redirect-in]: process connection from 192.168.2.2:44824: too many open streams
+0000 2024-07-07 10:31:49 ERROR [1674465238 38ms] inbound/redirect[redirect-in]: process connection from 192.168.2.2:34668: too many open streams
+0000 2024-07-07 10:31:49 ERROR [528537537 40ms] inbound/redirect[redirect-in]: process connection from 192.168.2.2:50190: too many open streams
+0000 2024-07-07 10:31:49 ERROR [1714550394 39ms] inbound/redirect[redirect-in]: process connection from 192.168.2.2:48282: too many open streams

**Comment by 1715173329** [comment]
See https://github.com/apernet/hysteria/issues/1073
