### ISSUE TITLE
GFWList 模式需要在 sing-box 内屏蔽 HTTPS/SVCB 记录

### ISSUE THREAD

**Issue by love4taylor** [immortalwrt/homeproxy#119]
1. 重启 homeproxy 保持 nftset 为空
2. 通过 `kdig www.v2ex.com HTTPS` 查询得到 `alpn="h3,h2" ipv4hint=104.20.47.180,104.20.48.180,172.67.35.211 ipv6hint=2606:4700:10::6814:2fb4,2606:4700:10::6814:30b4,2606:4700:10::ac43:23d3`
3. `nft list ruleset | grep` 以上任何一个 ip 都是空也就是说在 macOS 和 iOS 这种会请求 HTTPS 记录然后根据其进行通信的系统上会导致代理失效

**Comment by 1715173329** [comment]
d4045413cfe35d8bb4075d7f59dbd6bc5a6de883
