### ISSUE TITLE
怎么让这个插件支持firewall呢？

### ISSUE THREAD

**Issue by Kuron88** [immortalwrt/homeproxy#120]
怎么让这个插件支持firewall，而不是firewall4，firewall4比较很多插件不支持

**Comment by MarksonHon** [comment]
@Kuron88 自己修改源代码就行

**Comment by 1715173329** [comment]
不支持，也不会支持。

**Comment by Kuron88** [comment]
自己就是不会改啊，大佬怎么改

**Comment by MarksonHon** [comment]
@Kuron88 你先去学Golang编程语言与Linux防火墙，然后去修改singbox核心的源代码就行
