### ISSUE TITLE
server settings, HTTP/SOCKS等必须设置username & psasword

### ISSUE THREAD

**Issue by fo2w** [immortalwrt/homeproxy#13]
版本: 基于4.18日的master自己build
问题:
不知道是否有使用上的错误, 在配置server settings里面的http/socks代理时, username & password是必填项
未找到可以不设置的办法
但是某些情况下, 需要认证的代理使用起来不是很方便
期待:
是否考虑去除这个限制
或者
是否有其他替代方法

谢谢

**Comment by 1715173329** [comment]
最近两天看看，主要嫌 validate 麻烦

**Comment by fo2w** [comment]
大佬回复好快, 十分感谢, 辛苦了

**Comment by 1715173329** [comment]
431bf415fa1e
