### ISSUE TITLE
节点显示问题

### ISSUE THREAD

**Issue by LzwCracker** [immortalwrt/homeproxy#139]
![image](https://github.com/user-attachments/assets/6afa91c9-8e8b-4e65-b67d-9d43383cec96)
保存配置就生成多一个标签
更新订阅会跑到这个标签 不会在Node标签  怎么搞啊？

**Comment by muink** [comment]
这是正常的行为
来自订阅的节点会自成一组

**Comment by 1715173329** [comment]
别说，订阅分组这个挺好的，~~让我 kang 一下~~。

**Comment by muink** [comment]
> 别说，订阅分组这个挺好的，~~让我 kang 一下~~。

这就是pr #52的功能啊🤔

**Comment by 1715173329** [comment]
#52 只是修改 client 那边的显示名称吧。

**Comment by muink** [comment]
> #52 只是修改 client 那边的显示名称吧。

晚点我看看，应该在很前面的commit了

**Comment by 1715173329** [comment]
我 push 上去了😆

**Comment by muink** [comment]
用 URIfragment 作为组名这个点子不错 😮 
感觉我的 fork 也可以修修
