### ISSUE TITLE
 Dns服务器的设置问题

### ISSUE THREAD

**Issue by liaoke01** [immortalwrt/homeproxy#141]
dns服务器是否可以添加端口设置，我想让dns服务器和国内dns服务器一起走adguradhome

**Comment by muink** [comment]
为什么不把adguradhome放到hp前面
把adguradhome作为hp的上游dns根本毫无意义啊

**Comment by liaoke01** [comment]
> 为什么不把adguradhome放到hp前面 把adguradhome作为hp的上游dns根本毫无意义啊

hp有设置dns的监听端口吗？我在设置中没找到。不过经过我刚刚的测试，我发现把dns服务器设置为从wan口获取,国内dns服务器设置为ad Dns监听端口,国内国外的流量都是走ad.也可以分辨出不同的客户端,拦截也是生效的。如果是类似于daed,openclash的代理软件都有设置dns的监听端口， 将Ad作为上游，就只有127.0.0.1的流量。

**Comment by muink** [comment]
https://github.com/immortalwrt/homeproxy/blob/1553804ce8e1a2b6026af2ccfcdcef0e67a2951b/root/etc/config/homeproxy#L8-L9

**Comment by muink** [comment]
拦截当然是生效的
但是国外域名的dns请求就是走国内线路
依然会被污染和阻断，拿不到正确的dns结果，你hp不是开了个寂寞

**Comment by liaoke01** [comment]
> 拦截当然是生效的 但是国外域名的dns请求就是走国内线路 依然会被污染和阻断，拿不到正确的dns结果，你hp不是开了个寂寞

ad里面我添加了多个国内和国外服务器，然后并发请求。最先响应的一般是wan口dns,各大国外域名都是可以拿到正常的解析。处理速度也比较快。
![屏幕截图 2024-08-09 120746](https://github.com/user-attachments/assets/72659855-18c7-4996-86b1-66cb0af55a37)

**Comment by 1715173329** [comment]
不能。sb 不支持非标准端口。
