### ISSUE TITLE
界面出错

### ISSUE THREAD

**Issue by LzwCracker** [immortalwrt/homeproxy#145]
loadSubscriptionInfo: function(uciconfig) {
		var subs = {};
		for (var suburl of (uci.get(uciconfig, 'subscription', 'subscription_url') || [])) {
			const url = new URL(suburl);
			const urlhash = this.calcStringMD5(suburl.replace(/#.*$/, ''));
			subs[urlhash] = {
				"url": suburl.replace(/#.*$/, ''),
				"name": url.hash ? decodeURIComponent(url.hash.slice(1)) : url.hostname
			};
		}
		return subs;
	},
![123](https://github.com/user-attachments/assets/4db5b49c-c686-4334-9da6-cb8542d8551a)

**Comment by LzwCracker** [comment]
逗号出问题？

**Comment by LzwCracker** [comment]
好像是浏览器chrom惹的祸

**Comment by 1715173329** [comment]
issue 开错地方了。
