### ISSUE TITLE
dns错误

### ISSUE THREAD

**Issue by long1215** [immortalwrt/homeproxy#148]
gfwlist模式，8.8.8.8和223.5.5.5一样报错
+0000 2024-08-13 11:03:30 ERROR dns: exchange failed for www.netflix.com. IN A: context canceled
+0000 2024-08-13 11:03:30 ERROR dns: exchange failed for logs.netflix.com. IN A: context canceled
+0000 2024-08-13 11:03:30 ERROR dns: exchange failed for logs.netflix.com. IN AAAA: context deadline exceeded
+0000 2024-08-13 11:03:30 ERROR dns: exchange failed for www.netflix.com. IN AAAA: context canceled
+0000 2024-08-13 11:03:30 ERROR dns: exchange failed for appboot.netflix.com. IN AAAA: context canceled
+0000 2024-08-13 11:03:30 ERROR dns: exchange failed for tvos.prod.http1.netflix.com. IN AAAA: context canceled
+0000 2024-08-13 11:03:30 ERROR dns: exchange failed for tvos.prod.http1.netflix.com. IN A: context canceled
+0000 2024-08-13 11:03:30 ERROR dns: exchange failed for www.netflix.com. IN A: context canceled
+0000 2024-08-13 11:03:30 ERROR dns: exchange failed for www.netflix.com. IN A: context canceled
+0000 2024-08-13 11:03:30 ERROR dns: exchange failed for www.netflix.com. IN AAAA: context canceled
+0000 2024-08-13 11:03:30 ERROR dns: exchange failed for www.netflix.com. IN AAAA: context canceled
+0000 2024-08-13 11:03:30 ERROR dns: exchange failed for appboot.netflix.com. IN A: context canceled
+0000 2024-08-13 11:03:30 ERROR dns: exchange failed for www.netflix.com. IN AAAA: context canceled
+0000 2024-08-13 11:03:30 ERROR dns: exchange failed for www.netflix.com. IN A: context canceled
+0000 2024-08-13 11:03:30 ERROR dns: exchange failed for www.netflix.com. IN AAAA: context canceled
+0000 2024-08-13 11:03:30 ERROR dns: exchange failed for www.netflix.com. IN A: context canceled
+0000 2024-08-13 11:03:40 ERROR dns: exchange failed for www.netflix.com. IN A: context canceled
+0000 2024-08-13 11:03:40 ERROR dns: exchange failed for www.netflix.com. IN A: context canceled
+0000 2024-08-13 11:03:40 ERROR dns: exchange failed for www.netflix.com. IN AAAA: context deadline exceeded
+0000 2024-08-13 11:03:40 ERROR dns: exchange failed for www.netflix.com. IN AAAA: context canceled
+0000 2024-08-13 11:04:05 ERROR dns: exchange failed for www.netflix.com. IN A: context canceled
+0000 2024-08-13 11:04:05 ERROR dns: exchange failed for www.netflix.com. IN AAAA: context deadline exceeded
+0000 2024-08-13 11:04:05 ERROR dns: exchange failed for www.netflix.com. IN AAAA: context canceled
+0000 2024-08-13 11:04:05 ERROR dns: exchange failed for www.netflix.com. IN A: context canceled
+0000 2024-08-13 11:04:15 ERROR dns: exchange failed for www.netflix.com. IN A: context deadline exceeded
+0000 2024-08-13 11:04:15 ERROR dns: exchange failed for www.netflix.com. IN A: context canceled
+0000 2024-08-13 11:04:15 ERROR dns: exchange failed for www.netflix.com. IN AAAA: context canceled
+0000 2024-08-13 11:04:15 ERROR dns: exchange failed for www.netflix.com. IN AAAA: context canceled
+0000 2024-08-13 11:04:15 ERROR dns: exchange failed for www.netflix.com. IN AAAA: context canceled
+0000 2024-08-13 11:04:15 ERROR dns: exchange failed for www.netflix.com. IN A: context canceled
+0000 2024-08-13 11:04:29 ERROR dns: exchange failed for www.netflix.com. IN AAAA: context canceled
+0000 2024-08-13 11:04:29 ERROR dns: exchange failed for www.netflix.com. IN A: context deadline exceeded

**Comment by 1715173329** [comment]
代理节点问题。
