### ISSUE TITLE
请教代理常用端口，是指哪些端口

### ISSUE THREAD

**Issue by sztuxp** [immortalwrt/homeproxy#149]
目前需求，代理TCP 所有端口 + UDP 常用端口，如何配置

**Comment by muink** [comment]
不支持这样的操作

**Comment by sztuxp** [comment]
> 不支持这样的操作

那请教一下常用端口的列表是哪些？

**Comment by xlighting2017** [comment]
> > 不支持这样的操作
> 
> 那请教一下常用端口的列表是哪些？
<img width="765" alt="image" src="https://github.com/user-attachments/assets/9b28b70d-0327-4437-ab54-b0df0a003b89">

**Comment by 1715173329** [comment]
要分别代理端口，使用自定义路由即可。

**Comment by sztuxp** [comment]
> > > 不支持这样的操作
> > 
> > 
> > 那请教一下常用端口的列表是哪些？
> 
> <img alt="image" width="765" src="https://private-user-images.githubusercontent.com/25970065/358111969-9b28b70d-0327-4437-ab54-b0df0a003b89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2OTg2ODQsIm5iZiI6MTcyMzY5ODM4NCwicGF0aCI6Ii8yNTk3MDA2NS8zNTgxMTE5NjktOWIyOGI3MGQtMDMyNy00NDM3LWFiNTQtYjBkZjBhMDAzYjg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDA1MDYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3Yzc4MjEzMDM3N2U4ZDY5YTQzNzBiMzc2NzA0MmVhY2YyMjYxNWFkNWY3MWZhYWFhMWNmYzEwNDczMWM1OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R6-DyDekIc75oM7Ig88ZsM3F2nSQxhfVuE6QeKnIS84">

非常感谢！回复真快
