### ISSUE TITLE
大陆白名单路由模式 似乎不支持 代理域名列表？

### ISSUE THREAD

**Issue by douglarek** [immortalwrt/homeproxy#16]
![image](https://github.com/immortalwrt/homeproxy/assets/1488134/e914f9eb-9bc6-4376-839a-3f210b732c12)

代理机器 ping：

```
➜  ~ ping cn.bing.com               
PING china.bing123.com (202.89.233.101) 56(84) bytes of data.
64 bytes from 202.89.233.101 (202.89.233.101): icmp_seq=1 ttl=118 time=7.70 ms
64 bytes from 202.89.233.101 (202.89.233.101): icmp_seq=2 ttl=118 time=11.1 ms
^C
--- china.bing123.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1002ms
rtt min/avg/max/mdev = 7.704/9.397/11.090/1.693 ms
```

查看 sing-box 运行时配置文件（`/var/run/homeproxy/sing-box.json`）似乎也没有相应配置。

**Comment by 1715173329** [comment]
清理下缓存即可（后续不要再访问 cn 域名），或者将 cn-bing-com.cn.a-0001.a-msedge.net 加入代理列表

**Comment by douglarek** [comment]
> 清理下缓存即可（后续不要再访问 cn 域名），或者将 cn-bing-com.cn.a-0001.a-msedge.net 加入代理列表

这两个都用了，似乎不起作用，还是会自动跳转到 cn.bing.com。按理说 bing.com 如果被代理是不会跳 cn 域名的。另外 ping bing.com 走的 ipv6 ，会跟 ipv6 有关系吗

**Comment by 1715173329** [comment]
我没有办法复现你这个问题（同样开启了 v6），看看无痕模式会不会跳。

**Comment by douglarek** [comment]
> 我没有办法复现你这个问题（同样开启了 v6），看看无痕模式会不会跳。

很奇怪，我切换到全局路由模式一点问题没有。

**Comment by 1715173329** [comment]
你看下设置里面国家能改么

**Comment by douglarek** [comment]
> 你看下设置里面国家能改么

如果是跳到 cn 是改不了的。我刚才把国内 dns 设置为了 阿里云 dns 好了（感觉跟这个没关系，但是好了）。太玄学了，😃

**Comment by huijingfei** [comment]
这个问题我也遇到了，刚开始以为是homeproxy的问题，后来改了浏览器的DNS解决了。我用的是火狐，DoH设定为国内的DNS，linkedin.com一直跳转linkedin.cn，改为国外的DoH就好了，或者把DoH关了，保持默认也可以。

**Comment by stkevintan** [comment]
@huijingfei 这个确实是 homeproxy 的问题， homeproxy 按理来说就应该接管 dns 而不是客户端自己用别的dns 服务器。
但是我发现即使在 homeproxy 正确分流了 dns 也不奏效。原因是打开了 "绕过中国流量" 估计是根据 gfwlist 之类的把 linkedin 流量强行直连了。

**Comment by huijingfei** [comment]
> [@huijingfei](https://github.com/huijingfei) 这个确实是 homeproxy 的问题， homeproxy 按理来说就应该接管 dns 而不是客户端自己用别的dns 服务器。 但是我发现即使在 homeproxy 正确分流了 dns 也不奏效。原因是打开了 "绕过中国流量" 估计是根据 gfwlist 之类的把 linkedin 流量强行直连了。

先设置linkedin.com走代理，其次不要打开浏览器doh，doh会导致代理分流出问题，开启了doh所有的透明代理插件都没法正确分流。
