### ISSUE TITLE
Restarting the homeproxy service will automatically clear the cron job list that I have already configured.

### ISSUE THREAD

**Issue by thisIsIan-W** [immortalwrt/homeproxy#161]
OS version:
```shell
ImmortalWrt 23.05.2 r27625-416c8c5c91 / LuCI openwrt-23.05 branch git-24.079.19999-26165fd
```

Luci-app-homeproxy version:
```shell
luci-app-homeproxy_git-24.226.23824-9a48dd3_all
```

Steps to reproduce this issue:
1. Install luci-app-homeproxy;
2. Set scheduled tasks using the crontab -e command;
3. Executing `service homeproxy restart` or directly rebooting the system;
4. All the scheduled tasks I had previously set are gone.

**Comment by wd** [comment]
看这个代码好像没问题的样子，停止的时候只会删除那行能匹配的。
https://github.com/immortalwrt/homeproxy/blob/master/root/etc/init.d/homeproxy#L300
你或许可以自己 debug 下原因。

**Comment by HenTele** [comment]
5 15,16,23 * * * pkill -9 'home''proxy/scripts/update_resources.sh' ;find '/var/run/home''proxy/' -name update_resources-china_*.lock -delete ;eval '/etc/home''proxy/scripts/update_crond.sh'

写成这样，就匹配不到了。
`eval '/etc/home''proxy/scripts/update_crond.sh'`

**Comment by thisIsIan-W** [comment]
> 5 15,16,23 * * * pkill -9 'home''proxy/scripts/update_resources.sh' ;find '/var/run/home''proxy/' -name update_resources-china_*.lock -delete ;eval '/etc/home''proxy/scripts/update_crond.sh'
> 
> 写成这样，就匹配不到了。 `eval '/etc/home''proxy/scripts/update_crond.sh'`

Much appreciated!

**Comment by HenTele** [comment]
```bash
cat /etc/init.d/homeproxy |grep cron
                        echo -e "0 $auto_update_time * * * $HP_DIR/scripts/update_crond.sh" >> "/etc/crontabs/root"
                        /etc/init.d/cron restart
        sed -i "/update_crond.sh/d" "/etc/crontabs/root" 2>"/dev/null"
        /etc/init.d/cron restart >"/dev/null" 2>&1
```
开始匹配`update_crond.sh`了，所以，改成：
```text
5 15,16,23 * * * ps axf |grep -i 'home''proxy/scripts/update''_resources.sh' |grep -v 'grep' |awk '{print $1}' |xargs kill -9 ;find '/var/run/home''proxy/' -name update''_resources-china_*.lock -delete ;eval '/etc/home''proxy/scripts/update''_crond.sh'
```
