### ISSUE TITLE
无法获取cmliu/edgetunnel项目生成的订阅链接里的节点

### ISSUE THREAD

**Issue by Otakunwa** [immortalwrt/homeproxy#165]
非常感谢您开发的固件级插件！
不过我在homeproxy里遇到一个百思不得其解的问题：我按cmliu的[教程](https://github.com/cmliu/edgetunnel/commits/main/_worker.js)生成的订阅链接，在passwall及其它类似插件里都能成功获取节点，但是同一个链接，homeproxy就获取不了节点。麻烦您有空的时候看看好吗？先谢谢你啦！

**Comment by 1715173329** [comment]
没日志没示例推荐上街算一命。

**Comment by becksun0** [comment]
![image](https://github.com/user-attachments/assets/dc652d27-e8ce-417b-a9a7-7a49358034a6)

**Comment by 1715173329** [comment]
格式有误。

**Comment by becksun0** [comment]
这个订阅内容就是楼上提问说的那个项目生成的订阅链接，节点类型是vless，我试了那个项目的vless节点和trojan节点的订阅链接，日志都显示无效节点。

**Comment by Otakunwa** [comment]
> 没日志没示例推荐上街算一命。

承蒙大佬回复，欣喜若狂呀！

我回复慢了，不好意思呀。3楼的兄弟已经贴上了日志了，跟我这里的日志差不多，就是no valid node found. 

5楼的兄弟说得没错，这个链接的节点类型是vless，在passwall和openclash等插件里都能获取节点。估计您说的格式有误，就是这个节点类型的原因吧。

**Comment by 1715173329** [comment]
需要附上订阅链接内容。可以去掉隐私信息后发在此处，或者发送至我的邮箱，见主页。

本项目与其他项目无关。

**Comment by becksun0** [comment]
[Uploading trojan.txt…]()

**Comment by bolosmile** [comment]
我也是，日志上显示订阅添加了几十个节点，但是翻过去看，一个节点都显示不出来。

**Comment by bolosmile** [comment]
<img width="789" alt="iShot_2024-09-09_19 32 37" src="https://github.com/user-attachments/assets/90b2bc0b-f535-4302-9d7b-48ae5d84cb9b">
<img width="509" alt="iShot_2024-09-09_19 32 09" src="https://github.com/user-attachments/assets/b2332542-6ddc-49c9-9b64-b27c1ce2f8b6">

**Comment by funnyshao** [comment]
我也遇到了同样的问题，该如何解决啊

**Comment by idev19** [comment]
2024-11-07 16:18:06 [DAEMON] Service stopped.
2024-11-07 16:18:06 [SUBSCRIBE] 87 nodes added, 0 removed.
2024-11-07 16:18:06 [SUBSCRIBE] Successfully updated subscriptions.

然后没有界面没有节点

**Comment by whzhni2** [comment]
解决办法
![1731219923762](https://github.com/user-attachments/assets/ace75795-8e88-4a24-bb0c-30b9752cde97)

**Comment by FANYT** [comment]
![image](https://github.com/user-attachments/assets/227bde8f-f230-4267-887e-16e6b6433b3a)
刚好也碰到了这个问题，跟你一样的homeproxy，这样设置就可以了

**Comment by FANYT** [comment]
但我发现同一个订阅在homeproxy里面只有50几个节点，在passwall2里面有200多个节点，不知道为啥

**Comment by fbigun** [comment]
同样获取不了节点

**Comment by qyidc** [comment]
同样的问题，不知道现在解决了么？

**Comment by zlf179** [comment]
> 同样的问题，不知道现在解决了么？

其实不是问题 只是订阅链接后面加上`&flag=XXX`
XXXX填对应的客户端类型或者你想要的订阅格式 比如clash v2rayn就行了

**Comment by badmens** [comment]
默认包封装格式两种都试了，还是不能获取到节点信息。
