### ISSUE TITLE
在更新订阅时有一个bug

### ISSUE THREAD

**Issue by colahuang8** [immortalwrt/homeproxy#166]
在更新订阅时有一个bug, 它的机制似乎不是删除原来的站点信息，然后再添加的站点，而是替换改动的部分，其它的保留

这样导致的问题是，如果原先是trojan 结点，带了tls 字段，而这个结点一旦改动成ss 结点，就多出了tls 字段，而报错

希望能修复这个bug, 不然后面就不能自动订阅了，非常麻烦

例如，其中的一个outbound 形如  {
   "type": "shadowsocks",
   "tag": "",
   "routing_mark": 100,
   "server": "",
   "server_port": ...,
   "password": "",
   "method": "aes-128-gcm",
   "tls": {
    "enabled": true,
    "server_name": "...",
    "insecure": false
   }
  },

**Comment by colahuang8** [comment]
抱歉，我可能搞错版本了（如果这个版本也有同样的问题，也请修正一下吧）

**Comment by zhangqimao** [comment]
我之前cf的节点可以正常订阅 后面改动了一下设置之后再也无法订阅了 其他有几个机场大多数也不能订阅 不知道是什么原因 非常影响使用

**Comment by 1715173329** [comment]
c4351da0723864ee24529efd8c9d2a41c03c45d8
