### ISSUE TITLE
ERROR dns: exchange failed

### ISSUE THREAD

**Issue by Alex34020** [immortalwrt/homeproxy#168]
I’ve got the following errors in the sing-box client log, for example:

+0000 2024-08-30 19:33:19 ERROR dns: exchange failed for gs-loc.apple.com. IN HTTPS: context canceled
+0000 2024-08-30 19:33:19 ERROR dns: exchange failed for gs-loc.apple.com. IN A: context canceled
+0000 2024-08-30 19:34:15 ERROR dns: exchange failed for ssl.gstatic.com. IN HTTPS: context canceled
+0000 2024-08-30 19:34:55 ERROR dns: exchange failed for flow.logitech.io. IN A: context canceled
+0000 2024-08-30 19:36:01 ERROR dns: exchange failed for RU.lgtvsdp.com. IN A: context canceled
+0000 2024-08-30 19:39:22 ERROR dns: exchange failed for clients4.google.com. IN HTTPS: context canceled
+0000 2024-08-30 19:39:22 ERROR dns: exchange failed for clients4.google.com. IN A: context canceled

**Comment by 1715173329** [comment]
This means your network is not stable. Can be ignored safely.

**Comment by Alex34020** [comment]
Thanks for your cooperation. Would you please clarify, is there any way to fix it. I mean what parameters of my router should I check/edit to exclude such errors. Or it really has no sense? I would appreciate a lot for your answer.
