### ISSUE TITLE
vless流控，下拉菜单需要添加xtls-rprx-vision-udp443

### ISSUE THREAD

**Issue by shenlijun** [immortalwrt/homeproxy#18]
![微信截图_20230615183444](https://github.com/immortalwrt/homeproxy/assets/8860591/aa6305dc-da1a-4a42-b61f-197d7756d92b)

**Comment by shenlijun** [comment]
还是说sing-box的vless不会过滤udp？

**Comment by 1715173329** [comment]
sing-box 不支持 xtls-rprx-vision-udp443 流控，具体以 sing-box 为准。
