### ISSUE TITLE
【增强】DNS规则

### ISSUE THREAD

**Issue by Become-ILLUSORY** [immortalwrt/homeproxy#180]
我想添加如下dns规则，但是无从下手。
      {
        "type": "logical",
        "mode": "and",
        "rules": [
          {
            "rule_set": "geosite-geolocation-!cn",
            "invert": true
          },
          {
            "rule_set": "geoip-cn"
          }
        ],
        "server": "google",
        "client_subnet": "114.114.114.114/24" // Any China client IP address
      }

**Comment by muink** [comment]
Same as #172

**Comment by Become-ILLUSORY** [comment]
> Same as #172

我已经查看了你所提到的issues,但是inline ruleset并不在luci界面提供，我可以手写配置文件替换吗，但是sing-box配置文件不是都是homeproxy自动生成的吗？那么我应该在homeproxy那个界面手写这种ruleset呢？

**Comment by muink** [comment]
1.10的sing-box才支持
hp实现了但需要merge
https://github.com/muink/homeproxy/commits/dev/1.10
