### ISSUE TITLE
homeproxy dns服务器 自定义 仅能添加纯ip

### ISSUE THREAD

**Issue by 142857X1** [immortalwrt/homeproxy#182]
<dns被干扰了.访问网站大不开.
homeproxy的dns服务器 是不是走的梯子?>

带端口的如:127.0.0.1:5335 是无法添(本想配合mosdns)
dot/doh的加密dns也是无法添加

**Comment by 1715173329** [comment]
简单模式只接受传统 DNS 服务器，要自定义用自定义路由。不支持非标准端口。
