### ISSUE TITLE
Initialize rule-set take too much time to finish!

### ISSUE THREAD

**Issue by Arthur97172** [immortalwrt/homeproxy#184]
使用自定义规则每次启动在Sing-box客户端日志都会遇到这样的错误提示。。。 感觉是等待时间不够导致，但又不知道在哪里可以调整时间。

**Comment by 1715173329** [comment]
不能调整。
没有正确配置下载节点，或者节点垃圾。

**Comment by Arthur97172** [comment]
[homeproxy.zip](https://github.com/user-attachments/files/17044157/homeproxy.zip)
你看一下我的配置文件，启动时并没有提示错误，节点也是OK的。

**Comment by 1715173329** [comment]
1. 你的插件不是本项目发行
2. 没有配置下载节点，直连出站说明你网络不行

**Comment by muink** [comment]
@Arthur97172 似乎是我的项目
1. rule-set 更新周期可以设高点 比如 7d
2. rule-set 配置走代理更新
