### ISSUE TITLE
[Feature request] Support custom user-agent when subscribe/订阅界面支持自定义user-agent

### ISSUE THREAD

**Issue by gwd0715** [immortalwrt/homeproxy#188]
Please add a new feature that supports customized user-agent when subscribe, because some of the service suppliers only support mobile type user-agent to make a request. 
能否支持自定义user-agent呢？机场节点订阅有防火墙，只支持手机类型的user-agent请求，才会有节点信息返回。

**Comment by 1715173329** [comment]
应该去找你的机场，而不是本项目。
