### ISSUE TITLE
[访问控制-接口控制-监听接口]功能似乎对单独eth0, eth1, eth2这种物理接口设置无效

### ISSUE THREAD

**Issue by umlka** [immortalwrt/homeproxy#19]
路由模式:`大陆白名单`
**访问控制-接口控制-监听接口**功能下
只启用`eth0`, `eth1`, `eth2`这三个物理接口, 三个物理接口下的设备无法访问外网
启用`br-lan`, `br-lan`下的所有设备能够正常访问外网, 不指定接口也能正常访问

**Comment by 1715173329** [comment]
因为你的接口都在 br-lan 网桥内，流量是发到网桥处理的。
用 mac 或 ip 地址做访问控制即可。
