### ISSUE TITLE
开了`绕过中国流量`，就会无法访问需要代理的国外网站

### ISSUE THREAD

**Issue by HenTele** [immortalwrt/homeproxy#190]
开了`绕过中国流量`，就会无法访问需要代理的国外网站。`mt7621`的路由，上海电信。（从`luci-app-homeproxy_git-24.226.23824-9a48dd3_all.ipk`之后的版本开始出现的，必现的问题，回退到`luci-app-homeproxy_git-24.226.23824-9a48dd3_all.ipk`就没事）
而且，奇怪的是，另一个`x86_64`的主机，同样的`/etc/config/homeproxy`，`x86_64`的`homeproxy`就没有这个问题。
节点是套了cf-worker的vless+TLS+websocket。
自己编译的固件（`homeproxy`不是源码编译，`homeproxy的ipk`包来自 [这里](https://fantastic-packages.github.io/packages/releases/23.05/packages/x86_64/luci/)）。基本上需要的`nft`模块都启用了，`sing-box`编译的选项除了洋葱路由，也都启用了。`homeproxy`的四个资源文件也都是最新版本。

该怎么排查这个问题的原因？有没有错误日志之类的？

**Comment by HenTele** [comment]
mt7621和x86_64上的代理模式都是proxy_mode='redirect_tproxy'
mt7621改成`TUN TCP/UDP`就是可以正常访问需要代理的国外网站的，但是，mt7621上`TUN`模式的CPU占用率特别高，目前只能用`redirect_tproxy`

**Comment by arimitx** [comment]
试试隐身模式登入luci，然后重启homeproxy

**Comment by HenTele** [comment]
应该和缓存以无关，用终端reload也是一样的。目前倒是可以通过切换到tun模式，再切换回去，临时解决，我再观察观察吧。
