### ISSUE TITLE
luci-app-home proxy started intercepting all traffic after version 24.244.12351~68a36bf

### ISSUE THREAD

**Issue by YBS-PC** [immortalwrt/homeproxy#195]
AdguardHome with luci-app-homeproxy version 24.244.12351~68a36bf
![2024-10-10 152125](https://github.com/user-attachments/assets/f5f47680-c42b-43ae-a3d7-698763f5771f)

AdguardHome with luci-app-homeproxy version after 24.244.12351~68a36bf (d76d414+)
![2024-10-10 152100](https://github.com/user-attachments/assets/1176a77d-2ce0-4df1-8d4c-55b26b9e48ad)

**Comment by 1715173329** [comment]
AdGuardHome is not a part of homeproxy, we have nothing to do.
All DNS queries will redirect to the router, it's by design.
