### ISSUE TITLE
Sing-box里hysteria必须设置up_mbps和down_mbps才能使用

### ISSUE THREAD

**Issue by sougouzhinan** [immortalwrt/homeproxy#2]
UI里没有这俩选项,生成的配置里也没有,配置错误,启动失败

**Comment by 1715173329** [comment]
It was removed by mistake. Will fix it later today.

**Comment by 1715173329** [comment]
Yup, sorry for my silliness. Will fix it later.

**Comment by 1715173329** [comment]
fixed.
