### ISSUE TITLE
一个链接可以正常获取，另一个链接无法获取，什么原因？

### ISSUE THREAD

**Issue by xiaoxiongweihu** [immortalwrt/homeproxy#201]
### Bug description

一个订阅链接可以正常获取节点，另一个链接无法获取节点，什么原因？

### HomeProxy configuration

[homeproxy.zip](https://github.com/user-attachments/files/17399747/homeproxy.zip)

### sing-box configuration

[sing-box-c.zip](https://github.com/user-attachments/files/17399785/sing-box-c.zip)

### sing-box log

[sing-box-c-log.zip](https://github.com/user-attachments/files/17399791/sing-box-c-log.zip)

### OpenWrt/ImmortalWrt release

ImmortalWrt 23.05.4 r28061-399f9a1db3 / LuCI openwrt-23.05 branch git-24.265.44782-0ff45d8

### Device

无

### Terms

- [X] I confirm that the HomeProxy I installed is from official source, like GitHub artifacts or official ImmortalWrt opkg feeds.
- [X] I confirm that the Homeproxy I installed does not contain Clash mode support.
- [X] I confirm that the version of OpenWrt/ImmortalWrt I installed is >= 23.05.
- [X] I confirm that I have installed the latest version of HomeProxy and sing-box.
- [X] I confirm that I have read the sing-box documentation, understand the meaning of all the configuration items I added.
- [X] I confirm that I have not mixed iptables and nftables rules.
- [X] I confirm that I have selected all terms blindly.

**Comment by 1715173329** [comment]
> I confirm that I have selected all terms blindly.

This is great, you know.

**Comment by 1715173329** [comment]
在哪儿下的去哪儿问，不是本项目发行的插件。

**Comment by xiaoxiongweihu** [comment]
> > I confirm that I have selected all terms blindly.
> 
> This is great, you know.
> 在哪儿下的去哪儿问，不是本项目发行的插件。
勾选那个是因为我看不懂那玩意，但是按照要求上传了相应的文件，我是在immortalwrt的软件包下载的，我以为你这里是官方
![image](https://github.com/user-attachments/assets/e42f9268-b3b1-4ad2-8108-30e7b66b0554)

**Comment by 1715173329** [comment]
immortalwrt 从来就没发行过带 clash 支持的 homeproxy，你是从哪个宇宙的软件包下载的？
