### ISSUE TITLE
最新OP主线内核中，GFW模式无法正常工作

### ISSUE THREAD

**Issue by JiaY-shi** [immortalwrt/homeproxy#208]
### Bug description

由于主线dnsmasq变更https://github.com/openwrt/openwrt/commit/bd81d97e19e6cc6e33dc5ff852ece95bbc6be01e， 调整了配置目录，HP生成的gfw_list.conf的目录已经不再正确，导致GFW模式无法正常工作，望调整

### HomeProxy configuration

··

### sing-box configuration

··

### sing-box log

··

### OpenWrt/ImmortalWrt release

SNAPSHOT r27908-08484308fa

### Device

GL.iNet GL-MT6000

### Terms

- [X] I confirm that the HomeProxy I installed is from official source, like GitHub artifacts or official ImmortalWrt opkg feeds.
- [X] I confirm that the Homeproxy I installed does not contain Clash mode support.
- [X] I confirm that the version of OpenWrt/ImmortalWrt I installed is >= 23.05.
- [X] I confirm that I have installed the latest version of HomeProxy and sing-box.
- [X] I confirm that I have read the sing-box documentation, understand the meaning of all the configuration items I added.
- [X] I confirm that I have not mixed iptables and nftables rules.
- [X] I confirm that I have selected all terms blindly.

**Comment by 1715173329** [comment]
> I confirm that I have selected all terms blindly.
