### ISSUE TITLE
代理域名选项中,指定域名走代理,在配置中并没有走代理

### ISSUE THREAD

**Issue by rianjskis** [immortalwrt/homeproxy#210]
### Bug description

在大陆白名单模式下，在访问控制代理域名列表中填写指定域名走代理，实际在DNS中并没有走代理,在路由规则中也没有这个指定得域名

### Actual behavior

当我填写123.com走代理,在/var/run/homeproxy/sing-box-c.json配置中实际实现走了屏蔽DNS在路由规则中直接没有发现这条规则,然而在直连域名列表中填写得走直连得域名都是正常用国内DNS解析,路由规则也是走直连.
				"domain_keyword": [
					"123.com"
				],
				"query_type": [
					64,
					65
				],
				"server": "block-dns"
			}

### Expected behavior

希望能修复代理域名列表功能实现能填写要走代理得域名后能使用国内DNS解析,路由中走代理.

### Steps to reproduce

在访问控制中,代理域名列表选项中输入指定域名,重启HOMEPROXY可复现.

### HomeProxy configuration

1

### sing-box configuration

1

### sing-box log

1

### OpenWrt/ImmortalWrt release

23.05-SNAPSHOT r28091-bf1aaeac7b

### Device

FriendlyElec NanoPi R2S

### Terms

- [X] I confirm that the HomeProxy I installed is from official source, like GitHub artifacts or official ImmortalWrt opkg feeds.
- [X] I confirm that the Homeproxy I installed does not contain Clash mode support.
- [X] I confirm that the version of OpenWrt/ImmortalWrt I installed is >= 23.05.
- [X] I confirm that I have installed the latest version of HomeProxy and sing-box.
- [X] I confirm that I have read the sing-box documentation, understand the meaning of all the configuration items I added.
- [X] I confirm that I have not mixed iptables and nftables rules.
- [X] I confirm that I have selected all terms blindly.

**Comment by 1715173329** [comment]
> I confirm that I have selected all terms blindly.

**Comment by 1715173329** [comment]
大陆白名单下就是这么工作的。

**Comment by 1715173329** [comment]
本项目不支持所谓“旁路由”，这是错误用法。
