### ISSUE TITLE
sing-box 1.11.0开始将弃用部分选项，麻烦大佬留意一下

### ISSUE THREAD

**Issue by VIKINGYFY** [immortalwrt/homeproxy#213]
### Bug description

[31mERROR[0m[0000] legacy special outbounds is deprecated in sing-box 1.11.0 and will be removed in sing-box 1.13.0, checkout documentation for migration: https://sing-box.sagernet.org/migration/#migrate-legacy-special-outbounds-to-rule-actions
[31mFATAL[0m[0000] to continuing using this feature, set ENABLE_DEPRECATED_=true
2024-11-09 10:13:24 [DAEMON] Error: wrong client configuration detected.
2024-11-09 10:13:27 [DAEMON] Reloading service...
2024-11-09 10:13:31 [DAEMON] Service stopped.

### HomeProxy configuration

无

### sing-box configuration

无

### sing-box log

无

### OpenWrt/ImmortalWrt release

无

### Device

无

### Terms

- [X] I confirm that the HomeProxy I installed is from official source, like GitHub artifacts or official ImmortalWrt opkg feeds.
- [X] I confirm that the Homeproxy I installed does not contain Clash mode support.
- [X] I confirm that the version of OpenWrt/ImmortalWrt I installed is >= 23.05.
- [X] I confirm that I have installed the latest version of HomeProxy and sing-box.
- [X] I confirm that I have read the sing-box documentation, understand the meaning of all the configuration items I added.
- [X] I confirm that I have not mixed iptables and nftables rules.
- [X] I confirm that I have not modified system DNS settings, or enabled any other DNS servers like MosDNS and SmartDNS.
- [X] I confirm that I have selected all terms **blindly**.

**Comment by 1715173329** [comment]
> I confirm that I have selected all terms blindly
