### ISSUE TITLE
希望可以添加doh的功能

### ISSUE THREAD

**Issue by DifferentSparkler** [immortalwrt/homeproxy#214]
### Bug description

+0000 2024-11-11 00:47:12 ERROR [1464144338 184ms] dns: exchange failed for www.baidu.com. IN AAAA: context canceled
+0000 2024-11-11 00:47:12 ERROR [1464144338 184ms] dns: exchange failed for www.baidu.com. IN A: context canceled
+0000 2024-11-11 00:47:19 ERROR [1063893564 187ms] dns: exchange failed for testvideo.b-cdn.net. IN HTTPS: context canceled
+0000 2024-11-11 00:47:19 ERROR [4267965558 4.18s] dns: exchange failed for testvideo.b-cdn.net. IN A: context canceled
+0000 2024-11-11 00:47:27 ERROR [2256676741 72ms] dns: exchange failed for ogs.google.com. IN HTTPS: context canceled
+0000 2024-11-11 00:47:27 ERROR [3805702720 4.62s] dns: exchange failed for update.wps.cn. IN AAAA: context canceled
+0000 2024-11-11 00:47:27 ERROR [3528838641 4.80s] dns: exchange failed for ogs.google.com. IN A: context canceled
+0000 2024-11-11 00:47:27 ERROR [3805702720 4.62s] dns: exchange failed for update.wps.cn. IN A: context canceled
+0000 2024-11-11 00:47:35 ERROR [2264770934 1.57s] dns: exchange failed for api.ssl.so.com. IN A: context canceled
+0000 2024-11-11 00:47:35 ERROR [2264770934 1.57s] dns: exchange failed for mini.browser.360.cn. IN A: context canceled
+0000 2024-11-11 00:47:35 ERROR [2030299423 8.33s] dns: exchange failed for api.ssl.so.com. IN HTTPS: context canceled

### Actual behavior

![360截图20241111085328034](https://github.com/user-attachments/assets/c02e259b-6583-4fb0-b36e-526a2ddc86e0)
![360截图20241111085937769](https://github.com/user-attachments/assets/0ba0d105-33af-4b4b-aaab-5d46790d30ce)
![360截图20241111090004782](https://github.com/user-attachments/assets/2c07b679-0103-418e-b84b-b6f0b6826802)

### Expected behavior

希望可以添加doh的功能
首页直接显示代理IP的延迟和地址
优化一下分流规则

### HomeProxy configuration

config homeproxy 'infra'
        option __warning 'DO NOT EDIT THIS SECTION, OR YOU ARE ON YOUR OWN!'
        option common_port '22,53,80,143,443,465,853,873,993,995,8080,8443,9418'
        option mixed_port '5330'
        option redirect_port '5331'
        option tproxy_port '5332'
        option dns_port '5333'
        option china_dns_port '5334'
        option tun_name 'singtun0'
        option tun_addr4 '172.19.0.1/30'
        option tun_addr6 'fdfe:dcba:9876::1/126'
        option tun_mtu '9000'
        option tun_gso '0'
        option table_mark '100'
        option self_mark '100'
        option tproxy_mark '101'
        option tun_mark '102'

config homeproxy 'config'
        option main_node 'a83a757c5710b6993103f99a1c0fd3ac'
        option main_udp_node 'same'
        option dns_server '8.8.8.8'
        option routing_mode 'bypass_mainland_china'
        option proxy_mode 'redirect_tproxy'
        option ipv6_support '1'
        list china_dns_server '223.5.5.5'
        list china_dns_server '119.29.29.29'
        list china_dns_server '117.50.10.10'
        list china_dns_server '210.2.4.8'

config homeproxy 'control'
        option lan_proxy_mode 'disabled'
        list wan_proxy_ipv4_ips '91.105.192.0/23'
        list wan_proxy_ipv4_ips '91.108.4.0/22'
        list wan_proxy_ipv4_ips '91.108.8.0/22'
        list wan_proxy_ipv4_ips '91.108.16.0/22'
        list wan_proxy_ipv4_ips '91.108.12.0/22'
        list wan_proxy_ipv4_ips '91.108.20.0/22'
        list wan_proxy_ipv4_ips '91.108.56.0/22'
        list wan_proxy_ipv4_ips '149.154.160.0/20'
        list wan_proxy_ipv4_ips '185.76.151.0/24'
        list wan_proxy_ipv6_ips '2001:67c:4e8::/48'
        list wan_proxy_ipv6_ips '2001:b28:f23c::/48'
        list wan_proxy_ipv6_ips '2001:b28:f23d::/48'
        list wan_proxy_ipv6_ips '2001:b28:f23f::/48'
        list wan_proxy_ipv6_ips '2a0a:f280::/32'

config homeproxy 'routing'
        option sniff_override '1'
        option default_outbound 'direct-out'
        option udp_timeout '300'
        option bypass_cn_traffic '0'

config homeproxy 'dns'
        option dns_strategy 'prefer_ipv4'
        option default_server 'default-dns'

config homeproxy 'subscription'
        option auto_update '1'
        option allow_insecure '0'
        option packet_encoding 'xudp'
        option update_via_proxy '0'
        option filter_nodes 'blacklist'
        list filter_keywords '重置|到期|过期|剩余|套餐'
        list filter_keywords 'Expiration|Remaining'
        option auto_update_time '4'
        list subscription_url 'https://REDACTED'

config homeproxy 'server'
        option enabled '0'
        option auto_firewall '0'

config dns_rule 'nodes_domain'
        option label 'NodesDomain'
        option enabled '1'
        option mode 'default'
        list outbound 'any-out'
        option server 'default-dns'

### sing-box configuration

{
        "log": {
                "disabled": false,
                "level": "warn",
                "output": "/var/run/homeproxy/sing-box-c.log",
                "timestamp": true
        },
        "dns": {
                "servers": [
                        {
                                "tag": "default-dns",
                                "address": "10.0.1.1",
                                "detour": "direct-out"
                        },
                        {
                                "tag": "system-dns",
                                "address": "local",
                                "detour": "direct-out"
                        },
                        {
                                "tag": "block-dns",
                                "address": "rcode://name_error"
                        },
                        {
                                "tag": "main-dns",
                                "address": "tcp://8.8.8.8",
                                "detour": "main-out"
                        }
                ],
                "rules": [
                        {
                                "domain": "www.visa.com.hk",
                                "server": "default-dns"
                        }
                ],
                "disable_cache": false,
                "disable_expire": false,
                "independent_cache": false,
                "final": "main-dns"
        },
        "inbounds": [
                {
                        "type": "direct",
                        "tag": "dns-in",
                        "listen": "::",
                        "listen_port": 5333
                },
                {
                        "type": "mixed",
                        "tag": "mixed-in",
                        "listen": "::",
                        "listen_port": 5330,
                        "sniff": true,
                        "sniff_override_destination": true,
                        "set_system_proxy": false
                },
                {
                        "type": "redirect",
                        "tag": "redirect-in",
                        "listen": "::",
                        "listen_port": 5331,
                        "sniff": true,
                        "sniff_override_destination": true
                },
                {
                        "type": "tproxy",
                        "tag": "tproxy-in",
                        "listen": "::",
                        "listen_port": 5332,
                        "network": "udp",
                        "sniff": true,
                        "sniff_override_destination": true
                }
        ],
        "outbounds": [
                {
                        "type": "direct",
                        "tag": "direct-out",
                        "routing_mark": 100
                },
                {
                        "type": "block",
                        "tag": "block-out"
                },
                {
                        "type": "dns",
                        "tag": "dns-out"
                },
                {

                                },
                                "max_early_data": 2560,
                                "early_data_header_name": "Sec-WebSocket-Protocol"
                        }
                }
        ],
        "route": {
                "rules": [
                        {
                                "inbound": "dns-in",
                                "outbound": "dns-out"
                        },
                        {
                                "protocol": "dns",
                                "outbound": "dns-out"
                        }
                ],
                "rule_set": [
                ],
                "auto_detect_interface": true,
                "final": "main-out"
        }
}

### HomeProxy log

2024-11-11 08:46:55 [DAEMON] Reloading service...
2024-11-11 08:47:00 [DAEMON] Service stopped.
2024-11-11 08:47:05 [DAEMON] sing-box 1.9.7 started.

### sing-box log

+0000 2024-11-11 00:47:12 ERROR [1464144338 184ms] dns: exchange failed for www.baidu.com. IN AAAA: context canceled
+0000 2024-11-11 00:47:12 ERROR [1464144338 184ms] dns: exchange failed for www.baidu.com. IN A: context canceled
+0000 2024-11-11 00:47:19 ERROR [1063893564 187ms] dns: exchange failed for testvideo.b-cdn.net. IN HTTPS: context canceled
+0000 2024-11-11 00:47:19 ERROR [4267965558 4.18s] dns: exchange failed for testvideo.b-cdn.net. IN A: context canceled
+0000 2024-11-11 00:47:27 ERROR [2256676741 72ms] dns: exchange failed for ogs.google.com. IN HTTPS: context canceled
+0000 2024-11-11 00:47:27 ERROR [3805702720 4.62s] dns: exchange failed for update.wps.cn. IN AAAA: context canceled
+0000 2024-11-11 00:47:27 ERROR [3528838641 4.80s] dns: exchange failed for ogs.google.com. IN A: context canceled
+0000 2024-11-11 00:47:27 ERROR [3805702720 4.62s] dns: exchange failed for update.wps.cn. IN A: context canceled
+0000 2024-11-11 00:47:35 ERROR [2264770934 1.57s] dns: exchange failed for api.ssl.so.com. IN A: context canceled
+0000 2024-11-11 00:47:35 ERROR [2264770934 1.57s] dns: exchange failed for mini.browser.360.cn. IN A: context canceled
+0000 2024-11-11 00:47:35 ERROR [2030299423 8.33s] dns: exchange failed for api.ssl.so.com. IN HTTPS: context canceled
+0000 2024-11-11 00:47:35 ERROR [238235158 203ms] dns: exchange failed for mbsug.ssl.so.com. IN A: context canceled
+0000 2024-11-11 00:47:35 ERROR [2264770934 1.57s] dns: exchange failed for open.onebox.so.com. IN A: context canceled
+0000 2024-11-11 00:47:35 ERROR [826699120 204ms] dns: exchange failed for open.onebox.so.com. IN HTTPS: context canceled
+0000 2024-11-11 00:47:35 ERROR [2264770934 1.57s] dns: exchange failed for mbsug.ssl.so.com. IN HTTPS: context canceled
+0000 2024-11-11 00:47:35 ERROR [2030299423 8.33s] dns: exchange failed for mini.browser.360.cn. IN HTTPS: context canceled
+0000 2024-11-11 00:48:14 ERROR [1831312119 185ms] dns: exchange failed for ipv6-c088-sin001-ix.1.oca.nflxvideo.net. IN HTTPS: context canceled
+0000 2024-11-11 00:48:14 ERROR [2719477427 185ms] dns: exchange failed for ipv6-c088-sin001-ix.1.oca.nflxvideo.net. IN A: context canceled
+0000 2024-11-11 00:48:32 ERROR [1001159204 28ms] dns: exchange failed for openapi.baidu.com. IN HTTPS: context canceled
+0000 2024-11-11 00:48:32 ERROR [26324320 28ms] dns: exchange failed for openapi.baidu.com. IN A: context canceled
+0000 2024-11-11 00:48:32 ERROR [2225184889 182ms] dns: exchange failed for testvideo.b-cdn.net. IN HTTPS: context canceled
+0000 2024-11-11 00:48:32 ERROR [1347673621 183ms] dns: exchange failed for testvideo.b-cdn.net. IN A: context canceled
+0000 2024-11-11 00:48:44 ERROR [415197578 4.30s] dns: exchange failed for camo.githubusercontent.com. IN HTTPS: context canceled
+0000 2024-11-11 00:48:44 ERROR [1981098445 3.41s] dns: exchange failed for camo.githubusercontent.com. IN A: context canceled
+0000 2024-11-11 00:48:44 ERROR [402242085 4.31s] dns: exchange failed for avatars.githubusercontent.com. IN A: context canceled
+0000 2024-11-11 00:48:44 ERROR [1981098445 3.41s] dns: exchange failed for avatars.githubusercontent.com. IN HTTPS: context canceled
+0000 2024-11-11 00:49:01 ERROR [358919584 5.10s] dns: exchange failed for ai2news.com. IN HTTPS: context canceled
+0000 2024-11-11 00:49:01 ERROR [2305878466 2.65s] dns: exchange failed for ai2news.com. IN A: context canceled
+0000 2024-11-11 00:49:27 ERROR [599870354 9.56s] dns: exchange failed for xby.netlify.app. IN A: context canceled
+0000 2024-11-11 00:49:27 ERROR [1533837967 5.71s] dns: exchange failed for xby.netlify.app. IN HTTPS: context canceled
+0000 2024-11-11 00:49:33 ERROR [2763404121 179ms] dns: exchange failed for kesuen.ozsos.site. IN A: context canceled
+0000 2024-11-11 00:49:33 ERROR [2763404121 179ms] dns: exchange failed for kesuen.ozsos.site. IN HTTPS: context canceled
+0000 2024-11-11 00:49:59 ERROR [3105466239 1.29s] dns: exchange failed for viarotel.eu.org. IN A: context canceled
+0000 2024-11-11 00:49:59 ERROR [3069847103 2.63s] dns: exchange failed for ppio-cloud.feishu.cn. IN A: context canceled
+0000 2024-11-11 00:49:59 ERROR [3069847103 2.63s] dns: exchange failed for shylinux.com. IN HTTPS: context canceled
+0000 2024-11-11 00:49:59 ERROR [3069847103 2.63s] dns: exchange failed for viarotel.eu.org. IN HTTPS: context canceled
+0000 2024-11-11 00:49:59 ERROR [3105466239 1.29s] dns: exchange failed for ppio-cloud.feishu.cn. IN HTTPS: context canceled
+0000 2024-11-11 00:50:11 ERROR [1279107882 10.0s] dns: exchange failed for api.ssl.so.com. IN HTTPS: context canceled
+0000 2024-11-11 00:50:11 ERROR [3056947171 89ms] dns: exchange failed for papi.look.360.cn. IN A: context canceled
+0000 2024-11-11 00:50:11 ERROR [1279107882 10.0s] dns: exchange failed for query.rec.360.cn. IN A: context canceled
+0000 2024-11-11 00:50:11 ERROR [1279107882 10.0s] dns: exchange failed for api.ssl.so.com. IN A: context canceled
+0000 2024-11-11 00:50:11 ERROR [4131932243 5.17s] dns: exchange failed for papi.look.360.cn. IN HTTPS: context canceled
+0000 2024-11-11 00:50:11 ERROR [4131932243 5.17s] dns: exchange failed for browser6.qhimg.com. IN A: context canceled
+0000 2024-11-11 00:50:11 ERROR [1279107882 10.0s] dns: exchange failed for browser.360.cn. IN A: context canceled
+0000 2024-11-11 00:50:11 ERROR [3056947171 89ms] dns: exchange failed for query.rec.360.cn. IN HTTPS: context canceled
+0000 2024-11-11 00:50:11 ERROR [3096124877 301ms] dns: exchange failed for browser6.qhimg.com. IN HTTPS: context canceled
+0000 2024-11-11 00:50:19 ERROR [3332615571 7.21s] dns: exchange failed for alive.github.com. IN A: context canceled
+0000 2024-11-11 00:50:27 ERROR [1819366295 3.37s] dns: exchange failed for qurl.f.360.cn. IN A: context canceled
+0000 2024-11-11 00:50:32 ERROR [3154493186 9.68s] dns: exchange failed for www.dl.openwrt.ai. IN HTTPS: context canceled
+0000 2024-11-11 00:50:32 ERROR [442668243 8.52s] dns: exchange failed for www.dl.openwrt.ai. IN A: context canceled
+0000 2024-11-11 00:50:38 ERROR [1349752196 178ms] dns: exchange failed for browser.360.cn. IN A: context canceled
+0000 2024-11-11 00:50:38 ERROR [1349752196 178ms] dns: exchange failed for qurl.f.360.cn. IN A: context canceled
+0000 2024-11-11 00:50:45 ERROR [3641956283 7.13s] dns: exchange failed for mbsug.ssl.so.com. IN A: context canceled
+0000 2024-11-11 00:50:45 ERROR [3641956283 7.13s] dns: exchange failed for open.onebox.so.com. IN HTTPS: context canceled
+0000 2024-11-11 00:50:45 ERROR [3803993416 182ms] dns: exchange failed for mbsug.ssl.so.com. IN HTTPS: context canceled
+0000 2024-11-11 00:50:45 ERROR [113838235 10.4s] dns: exchange failed for api.ssl.so.com. IN A: context canceled
+0000 2024-11-11 00:50:45 ERROR [113838235 10.4s] dns: exchange failed for api.ssl.so.com. IN HTTPS: context canceled
+0000 2024-11-11 00:50:45 ERROR [113838235 10.4s] dns: exchange failed for open.onebox.so.com. IN A: context canceled
+0000 2024-11-11 00:50:50 ERROR [1178070586 184ms] dns: exchange failed for pubstatic.b0.upaiyun.com. IN A: context canceled
+0000 2024-11-11 00:50:50 ERROR [377134662 3.56s] dns: exchange failed for api.ip.sb. IN HTTPS: context canceled
+0000 2024-11-11 00:50:50 ERROR [4009136930 3.56s] dns: exchange failed for api-v3.speedtest.cn. IN HTTPS: context canceled
+0000 2024-11-11 00:50:50 ERROR [4009136930 3.56s] dns: exchange failed for 2024.ip138.com. IN A: context canceled
+0000 2024-11-11 00:50:50 ERROR [1178070586 184ms] dns: exchange failed for pubstatic.b0.upaiyun.com. IN HTTPS: context canceled
+0000 2024-11-11 00:50:50 ERROR [377134662 3.56s] dns: exchange failed for api.ip.sb. IN A: context canceled
+0000 2024-11-11 00:50:50 ERROR [4009136930 3.56s] dns: exchange failed for dns.ipv4dns.com. IN HTTPS: context canceled
+0000 2024-11-11 00:50:50 ERROR [1178070586 184ms] dns: exchange failed for 2024.ip138.com. IN HTTPS: context canceled
+0000 2024-11-11 00:50:50 ERROR [1178070586 184ms] dns: exchange failed for api-v3.speedtest.cn. IN A: context canceled
+0000 2024-11-11 00:50:50 ERROR [4009136930 3.56s] dns: exchange failed for dns.ipv4dns.com. IN A: context canceled
+0000 2024-11-11 00:51:11 ERROR [3948771702 182ms] dns: exchange failed for www.baidu.com. IN A: context canceled
+0000 2024-11-11 00:51:42 ERROR [159910634 176ms] dns: exchange failed for content-autofill.googleapis.com. IN HTTPS: context canceled
+0000 2024-11-11 00:52:12 ERROR [818411547 189ms] dns: exchange failed for hiya.browser.360.cn. IN A: context canceled
+0000 2024-11-11 00:53:13 ERROR [144646093 174ms] dns: exchange failed for www.baidu.com. IN HTTPS: context canceled
+0000 2024-11-11 00:53:13 ERROR [1803241084 175ms] dns: exchange failed for www.baidu.com. IN A: context canceled
+0000 2024-11-11 00:53:37 ERROR [2606167063 177ms] dns: exchange failed for client.wns.windows.com. IN AAAA: context canceled
+0000 2024-11-11 00:53:46 ERROR [1695224776 7.80s] dns: exchange failed for alive.github.com. IN A: context canceled
+0000 2024-11-11 00:54:11 ERROR [563389205 179ms] dns: exchange failed for content-autofill.googleapis.com. IN HTTPS: context canceled
+0000 2024-11-11 00:54:11 ERROR [3524217049 179ms] dns: exchange failed for content-autofill.googleapis.com. IN A: context canceled
+0000 2024-11-11 00:55:04 ERROR [3267494652 180ms] dns: exchange failed for qurl.f.360.cn. IN A: context canceled

### OpenWrt/ImmortalWrt release

24.10-SNAPSHOT r0-a01f802

### Device

ZN M2

### Terms

- [X] I confirm that the HomeProxy I installed is from official source, like GitHub artifacts or official ImmortalWrt opkg feeds.
- [X] I confirm that the Homeproxy I installed does not contain Clash mode support.
- [X] I confirm that the version of OpenWrt/ImmortalWrt I installed is >= 23.05.
- [X] I confirm that I have installed the latest version of HomeProxy and sing-box.
- [X] I confirm that I have read the sing-box documentation, understand the meaning of all the configuration items I added.
- [X] I confirm that I have not mixed iptables and nftables rules.
- [X] I confirm that I have not modified system DNS settings, or enabled any other DNS servers like MosDNS and SmartDNS.
- [X] I confirm that I have selected all terms **blindly**.

**Comment by 1715173329** [comment]
1. 使用错误 issue 模板。
2. 非自定义路由模式不会支持。
