### ISSUE TITLE
[功能需求] 希望 homeproxy 的国外组 dns 配置开放端口给用户配置

### ISSUE THREAD

**Issue by ximiTech** [immortalwrt/homeproxy#22]
天灵灵大佬，已在 sing-box 项目提出请求，https://github.com/SagerNet/sing-box/issues/729
并且有一位大佬 [liaoliaots] 回复如下：

sing-box支持如下格式的 dns

tcp://x.x.x.x:3305
udp://x.x.x.x:3306
tls://x.x.x.x:3307
https://x.x.x.x:3308/dns-query
quic://xxx.com:3309
h3://x.x.x.x:3310/dns-query

希望 homeproxy 能支持上，谢谢！

**Comment by 1715173329** [comment]
需要上游支持。
