### ISSUE TITLE
openwrt 23.05报权限错误

### ISSUE THREAD

**Issue by sjkhsl** [immortalwrt/homeproxy#223]
### Bug description

运行自定义路由时会报错：Permission Error: Download permission denied

### HomeProxy configuration

root@OpenWrt:~# cat /etc/config/homeproxy

config homeproxy 'infra'
option __warning 'DO NOT EDIT THIS SECTION, OR YOU ARE ON YOUR OWN!'
option common_port '22,53,80,143,443,465,853,873,993,995,8080,8443,9418'
option mixed_port '5330'
option redirect_port '5331'
option tproxy_port '5332'
option dns_port '5333'
option china_dns_port '5334'
option tun_name 'singtun0'
option tun_addr4 '172.19.0.1/30'
option tun_addr6 'fdfe:dcba:9876::1/126'
option tun_mtu '9000'
option tun_gso '0'
option table_mark '100'
option self_mark '100'
option tproxy_mark '101'
option tun_mark '102'

config homeproxy 'config'
option routing_mode 'custom'
option routing_port 'common'
option proxy_mode 'redirect_tproxy'
option ipv6_support '1'

config homeproxy 'control'
option lan_proxy_mode 'disabled'
list wan_proxy_ipv4_ips '91.105.192.0/23'
list wan_proxy_ipv4_ips '91.108.4.0/22'
list wan_proxy_ipv4_ips '91.108.8.0/22'
list wan_proxy_ipv4_ips '91.108.16.0/22'
list wan_proxy_ipv4_ips '91.108.12.0/22'
list wan_proxy_ipv4_ips '91.108.20.0/22'
list wan_proxy_ipv4_ips '91.108.56.0/22'
list wan_proxy_ipv4_ips '149.154.160.0/20'
list wan_proxy_ipv4_ips '185.76.151.0/24'
list wan_proxy_ipv6_ips '2001:67c:4e8::/48'
list wan_proxy_ipv6_ips '2001:b28:f23c::/48'
list wan_proxy_ipv6_ips '2001:b28:f23d::/48'
list wan_proxy_ipv6_ips '2001:b28:f23f::/48'
list wan_proxy_ipv6_ips '2a0a:f280::/32'

config homeproxy 'routing'
option sniff_override '1'
option default_outbound 'nil'
option udp_timeout '300'
option bypass_cn_traffic '0'

config homeproxy 'dns'
option dns_strategy 'prefer_ipv4'
option default_server 'proxy_dns'
option default_strategy 'prefer_ipv4'
option client_subnet '1.0.1.0'

config homeproxy 'subscription'
option auto_update '0'
option allow_insecure '0'
option packet_encoding 'xudp'
option update_via_proxy '0'
option filter_nodes 'blacklist'
list filter_keywords '重置|到期|过期|剩余|套餐'
list filter_keywords 'Expiration|Remaining'

config homeproxy 'server'
option enabled '0'
option auto_firewall '0'

config dns_rule 'nodes_domain'
option label 'NodesDomain'
option enabled '1'
option mode 'default'
list outbound 'any-out'
option server 'default-dns

config node 'c2df72129e61xxxxxxxxxxxxx'
option label '香港'
option type 'vless'
option address 'xxx.xxx.xxx'
option port 'xxx'
option uuid 'xxxxxxx-57xx-4axx-xx95-0xxxxxx2'
option transport 'ws'
option tls '1'
option ws_path '/xxxx'
option packet_encoding 'xudp'

config ruleset 'CN_Domain'
option label 'CN_Domain'
option enabled '1'
option type 'remote'
option format 'binary'
option url 'https://github.com/DustinWin/ruleset_geodata/raw/refs/heads/sing-box-ruleset/cn.srs'
option outbound 'proxy'

config ruleset 'CN_IP'
option label 'CN_IP'
option enabled '1'
option type 'remote'
option format 'binary'
option url 'https://github.com/DustinWin/ruleset_geodata/raw/refs/heads/sing-box-ruleset/cnip.srs'
option outbound 'proxy'

config ruleset 'Proxy'
option label 'Proxy'
option enabled '1'
option type 'remote'
option format 'binary'
option url 'https://github.com/DustinWin/ruleset_geodata/raw/refs/heads/sing-box-ruleset/proxy.srs'
option outbound 'proxy'

config ruleset 'Ads'
option label 'Ads'
option enabled '1'
option type 'remote'
option format 'binary'
option url 'https://github.com/DustinWin/ruleset_geodata/raw/refs/heads/sing-box-ruleset/ads.srs'
option outbound 'proxy'

config dns_server 'local_dns'
option label 'local_dns'
option enabled '1'
option address 'https://223.5.5.5/dns-query'
option resolve_strategy 'prefer_ipv4'
option outbound 'direct-out'

config dns_server 'proxy_dns'
option label 'proxy_dns'
option enabled '1'
option address 'https://8.8.8.8/dns-query'
option resolve_strategy 'prefer_ipv4'
option outbound 'proxy'

config dns_server 'other_dns'
option label 'other_dns'
option enabled '1'
option address 'https://8.8.8.8/dns-query'
option resolve_strategy 'prefer_ipv4'
option outbound 'proxy'
option client_subnet '1.0.1.0'

config dns_rule 'dns_proxy_rule'
option label 'dns_proxy_rule'
option enabled '1'
option mode 'default'
list rule_set 'Proxy'
option server 'proxy_dns'

config dns_rule 'dns_local_rule'
option label 'dns_local_rule'
option enabled '1'
option mode 'default'
list rule_set 'CN_Domain'
list rule_set 'CN_IP'
option server 'local_dns'

config dns_rule 'dns_other_rule'
option label 'dns_other_rule'
option enabled '1'
option mode 'default'
list rule_set 'CN_IP'
option server 'proxy_dns'
option client_subnet '1.0.1.0'

config routing_node 'proxy'
option label 'proxy'
option enabled '1'
option node 'c2df72129e61xxxxxxxxxxxxxxxxxxx'
option domain_strategy 'prefer_ipv4'

config routing_rule 'QUIC_Block'
option label 'QUIC_Block'
option enabled '1'
option mode 'default'
list protocol 'quic'
option source_ip_is_private '0'
option ip_is_private '0'
option outbound 'block-out'

config routing_rule 'proxy_route'
option label 'proxy_route'
option enabled '1'
option mode 'default'
option source_ip_is_private '0'
option ip_is_private '0'
list rule_set 'Proxy'
option outbound 'proxy'

config routing_rule 'local_route'
option label 'local_route'
option enabled '1'
option mode 'default'
option source_ip_is_private '0'
option ip_is_private '0'
list rule_set 'CN_Domain'
list rule_set 'CN_IP'
option outbound 'direct-out'

### sing-box configuration

配置应该没问题

### sing-box log

2024-11-23 22:00:51 [DAEMON] Reloading service...
2024-11-23 22:00:55 [DAEMON] Service stopped.
2024-11-23 22:03:34 [DAEMON] Reloading service...
2024-11-23 22:03:37 [DAEMON] Service stopped.
2024-11-23 22:03:38 [DAEMON] sing-box 1.9.7 started.
2024-11-23 22:04:09 [DAEMON] Reloading service...
2024-11-23 22:04:13 [DAEMON] Service stopped.
2024-11-23 22:15:26 [DAEMON] Service stopped.
2024-11-23 22:15:46 [DAEMON] Reloading service...
2024-11-23 22:15:49 [DAEMON] Service stopped.
2024-11-23 22:15:50 [DAEMON] sing-box 1.9.7 started.
2024-11-23 22:17:03 [DAEMON] Service stopped.
2024-11-23 22:17:04 [DAEMON] sing-box 1.9.7 started.
2024-11-23 22:17:28 [DAEMON] Reloading service...
2024-11-23 22:17:31 [DAEMON] Service stopped.
2024-11-23 22:22:27 [DAEMON] Reloading service...
2024-11-23 22:22:29 [DAEMON] Service stopped.
2024-11-23 22:22:30 [DAEMON] sing-box 1.9.7 started.
2024-11-23 22:23:19 [DAEMON] Reloading service...
2024-11-23 22:23:22 [DAEMON] Service stopped.
2024-11-23 22:27:17 [DAEMON] Service stopped.
2024-11-23 22:27:41 [DAEMON] Reloading service...
2024-11-23 22:27:44 [DAEMON] Service stopped.
2024-11-23 22:27:45 [DAEMON] sing-box 1.9.7 started.
2024-11-23 22:28:05 [DAEMON] Reloading service...
2024-11-23 22:28:09 [DAEMON] Service stopped.
2024-11-23 22:28:35 [DAEMON] Service stopped.
2024-11-23 22:28:41 [DAEMON] Reloading service...
2024-11-23 22:28:44 [DAEMON] Service stopped.
2024-11-23 22:28:45 [DAEMON] sing-box 1.9.7 started.
2024-11-23 22:29:23 [DAEMON] Reloading service...
2024-11-23 22:29:27 [DAEMON] Service stopped.
2024-11-23 22:38:07 [DAEMON] Service stopped.
2024-11-23 22:38:25 [DAEMON] Reloading service...
2024-11-23 22:38:28 [DAEMON] Service stopped.
2024-11-23 22:38:29 [DAEMON] sing-box 1.9.7 started.
2024-11-23 22:38:51 [DAEMON] Reloading service...
2024-11-23 22:38:55 [DAEMON] Service stopped.

### OpenWrt/ImmortalWrt release

23.05-SNAPSHOT r24138-cd9998ef1b

### Device

j4125

### Additional information

openwrt 23.05已经没有/var目录，/etc/init.d/homeproxy中RUN_DIR="/var/run/homeproxy"修改为/tmp/run/homeproxy，依旧报错。

### Terms

- [X] I confirm that the HomeProxy I installed is from official source, like GitHub artifacts or official ImmortalWrt opkg feeds.
- [X] I confirm that the Homeproxy I installed does not contain Clash mode support.
- [X] I confirm that the version of OpenWrt/ImmortalWrt I installed is >= 23.05.
- [X] I confirm that I have installed the latest version of HomeProxy and sing-box.
- [X] I confirm that I have read the sing-box documentation, understand the meaning of all the configuration items I added.
- [X] I confirm that I have not mixed iptables and nftables rules.
- [X] I confirm that I have not modified system DNS settings, or enabled any other DNS servers like MosDNS and SmartDNS.
- [ ] I confirm that I have selected all terms **blindly**.

**Comment by 1715173329** [comment]
什么权限错误，哪一页，图呢

**Comment by sjkhsl** [comment]
> Permission Error: Download permission denied

日志信息就提示 Permission Error: Download permission denied

**Comment by 1715173329** [comment]
无有效信息以诊断此问题。

**Comment by pengliaoye** [comment]
@itispip  有解决么

**Comment by itispip** [comment]
> [@itispip](https://github.com/itispip) 有解决么

不知道。已经不用HomeProxy了，直接用singboc
