### ISSUE TITLE
更新后出了问题

### ISSUE THREAD

**Issue by KH9CQ** [immortalwrt/homeproxy#224]
### Bug description

如下：
TypeError
Class must be a descendent of CBIAbstractValue
  at ClassConstructor.option (http://10.10.10.1/luci-static/resources/form.js?v=git-24.272.29284-d386ad6:73:9)
  at renderNodeSettings (http://10.10.10.1/luci-static/resources/view/homeproxy/node.js?v=git-24.272.29284-d386ad6:58:54)
  at ClassConstructor.render (http://10.10.10.1/luci-static/resources/view/homeproxy/node.js?v=git-24.272.29284-d386ad6:68:203)

TypeError
Class must be a descendent of CBIAbstractValue
  at ClassConstructor.option (http://10.10.10.1/luci-static/resources/form.js?v=git-24.272.29284-d386ad6:73:9)
  at ClassConstructor.render (http://10.10.10.1/luci-static/resources/view/homeproxy/server.js?v=git-24.272.29284-d386ad6:37:54)
![546](https://github.com/user-attachments/assets/a4c5c5f9-dbee-4162-8afe-b5120b42633f)
![912](https://github.com/user-attachments/assets/33cbfaec-daf2-4555-af99-a3689af2967a)

### Steps to reproduce

点节点设置和服务器设置出现错误

### HomeProxy configuration

config homeproxy 'infra'
        option __warning 'DO NOT EDIT THIS SECTION, OR YOU ARE ON YOUR OWN!'
        option common_port '22,53,80,143,443,465,853,873,993,995,8080,8443,9418'
        option mixed_port '5330'
        option redirect_port '5331'
        option tproxy_port '5332'
        option dns_port '5333'
        option china_dns_port '5334'
        option tun_name 'singtun0'
        option tun_addr4 '172.19.0.1/30'
        option tun_addr6 'fdfe:dcba:9876::1/126'
        option tun_mtu '9000'
        option tun_gso '0'
        option table_mark '100'
        option self_mark '100'
        option tproxy_mark '101'
        option tun_mark '102'

config homeproxy 'config'
        option routing_mode 'custom'
        option routing_port 'common'
        option proxy_mode 'redirect_tproxy'
        option ipv6_support '0'

config homeproxy 'control'
        option lan_proxy_mode 'disabled'
        list wan_proxy_ipv4_ips '91.105.192.0/23'
        list wan_proxy_ipv4_ips '91.108.4.0/22'
        list wan_proxy_ipv4_ips '91.108.8.0/22'
        list wan_proxy_ipv4_ips '91.108.16.0/22'
        list wan_proxy_ipv4_ips '91.108.12.0/22'
        list wan_proxy_ipv4_ips '91.108.20.0/22'
        list wan_proxy_ipv4_ips '91.108.56.0/22'
        list wan_proxy_ipv4_ips '149.154.160.0/20'
        list wan_proxy_ipv4_ips '185.76.151.0/24'

config homeproxy 'routing'
        option sniff_override '0'
        option default_outbound 'defaut_node'
        option udp_timeout '300'
        option bypass_cn_traffic '1'

config homeproxy 'dns'
        option dns_strategy 'prefer_ipv4'
        option default_server 'Google'
        option disable_cache '1'

config homeproxy 'subscription'
        option auto_update '1'
        option allow_insecure '0'
        option packet_encoding 'xudp'
        option update_via_proxy '1'
        option filter_nodes 'blacklist'
        list filter_keywords '重置|到期|过期|剩余|套餐'
        list filter_keywords 'Expiration|Remaining'
        option auto_update_time '2'

config homeproxy 'server'
        option enabled '0'
        option auto_firewall '0'

config dns_rule 'nodes_domain'
        option label 'NodesDomain'
        option enabled '1'
        option mode 'default'
        list outbound 'any-out'
        option server 'default-dns'

config routing_node 'defaut_node'
        option label 'defaut_node'
        option enabled '1'
        option node '2a40d664a091e6e529d9e599d5be478a'

config routing_rule 'direct'
        option label 'direct'
        option enabled '1'
        option mode 'default'
        option source_ip_is_private '0'
        option ip_is_private '0'
        option rule_set_ip_cidr_match_source '0'
        option outbound 'direct-out'
        list rule_set 'cnip'
        list rule_set 'cnsite'

config dns_server 'Tencent'
        option label 'Tencent'
        option enabled '0'
        option address '119.29.29.29'
        option outbound 'direct-out'

config dns_server 'Aliyun'
        option label 'Aliyun'
        option enabled '1'
        option address 'quic://dns.alidns.com'
        option outbound 'direct-out'
        option address_resolver 'default-dns'

config dns_server 'Google'
        option label 'Google'
        option enabled '1'
        option address 'https://dns.google/dns-query'
        option address_strategy 'ipv4_only'
        option resolve_strategy 'ipv4_only'
        option outbound 'defaut_node'
        option address_resolver 'default-dns'
        option client_subnet 'x.x.x.x'

config ruleset 'cnip'
        option label 'cnip'
        option enabled '1'
        option type 'remote'
        option format 'binary'
        option url 'https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/sing/geo-lite/geoip/cn.srs'
        option outbound 'defaut_node'

config ruleset 'cnsite'
        option label 'cnsite'
        option enabled '1'
        option type 'remote'
        option format 'binary'
        option url 'https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/sing/geo-lite/geosite/cn.srs'
        option outbound 'defaut_node'

config ruleset 'openai'
        option label 'openai'
        option enabled '1'
        option type 'remote'
        option format 'binary'
        option url 'https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/sing/geo-lite/geosite/openai.srs'
        option outbound 'defaut_node'

config ruleset 'tiktok'
        option label 'tiktok'
        option enabled '1'
        option type 'remote'
        option format 'binary'
        option url 'https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/sing/geo-lite/geosite/tiktok.srs'
        option outbound 'defaut_node'

config routing_node 'chatgpt_node'
        option label 'sg_node'
        option enabled '1'
        option node 'b8dd2ed517b1235a0862be42878e1df4'

config ruleset 'x_ip'
        option label 'x_ip'
        option enabled '0'
        option type 'remote'
        option format 'binary'
        option url 'https://github.com/MetaCubeX/meta-rules-dat/blob/sing/geo-lite/geoip/twitter.srs'
        option outbound 'defaut_node'

config ruleset 'x_site'
        option label 'x_site'
        option enabled '0'
        option type 'remote'
        option format 'binary'
        option url 'https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/sing/geo-lite/geosite/twitter.srs'
        option outbound 'defaut_node'

config ruleset 'microsoft'
        option label 'microsoft'
        option enabled '0'
        option type 'remote'
        option format 'binary'
        option url 'https://github.com/MetaCubeX/meta-rules-dat/blob/sing/geo-lite/geosite/microsoft.srs'
        option outbound 'defaut_node'

config ruleset 'customsite'
        option label 'gemini'
        option enabled '1'
        option type 'local'
        option format 'source'
        option path '/etc/homeproxy/ruleset/gemini.json'

config dns_rule 'cn_dns'
        option label 'cn_dns'
        option enabled '1'
        option mode 'default'
        option server 'Aliyun'
        list rule_set 'cnip'
        list rule_set 'cnsite'

config dns_rule 'google_dns'
        option label 'sg_dns'
        option enabled '1'
        option mode 'default'
        option ip_version '4'
        option server 'Google'
        list rule_set 'openai'
        list rule_set 'tiktok'
        list rule_set 'customsite'

config routing_rule 'custom_site'
        option label 'sg'
        option enabled '1'
        option mode 'default'
        option source_ip_is_private '0'
        option ip_is_private '0'
        option rule_set_ip_cidr_match_source '0'
        option outbound 'chatgpt_node'
        option ip_version '4'
        list rule_set 'openai'
        list rule_set 'tiktok'
        list rule_set 'customsite'

config routing_rule 'x'
        option label 'x'
        option enabled '0'
        option mode 'default'
        option source_ip_is_private '0'
        option ip_is_private '0'
        list rule_set 'x_ip'
        list rule_set 'x_site'
        option rule_set_ip_cidr_match_source '1'
        option outbound 'chatgpt_node'

config routing_rule 'pikpak_down'
        option label 'pikpak_down'
        option enabled '1'
        option mode 'default'
        option source_ip_is_private '0'
        option ip_is_private '0'
        list rule_set 'pikpak_download'
        option rule_set_ip_cidr_match_source '0'
        option outbound 'direct-out'

config ruleset 'pikpak_download'
        option label 'pikpak_download'
        option enabled '1'
        option type 'local'
        option format 'source'
        option path '/etc/homeproxy/ruleset/pikpak_download.json'

config ruleset 'REJECT_pikpak'
        option label 'pikpak_REJECT'
        option enabled '1'
        option type 'local'
        option format 'source'
        option path '/etc/homeproxy/ruleset/pikpak_REJECT.json'

config routing_rule 'pikpak'
        option label 'pikpak_access'
        option enabled '1'
        option mode 'default'
        option source_ip_is_private '0'
        option ip_is_private '0'
        list rule_set 'REJECT_pikpak'
        option rule_set_ip_cidr_match_source '0'
        option outbound 'block-out'

config ruleset 'Direct_bytefcdnrd'
        option label 'Direct_bytefcdnrd'
        option enabled '1'
        option type 'local'
        option format 'source'
        option path '/etc/homeproxy/ruleset/Direct_bytefcdnrd.json'

config routing_rule 'microsoft_rule'
        option label 'microsoft_rule'
        option enabled '0'
        option mode 'default'
        option source_ip_is_private '0'
        option ip_is_private '0'
        list rule_set 'microsoft'
        option rule_set_ip_cidr_match_source '0'
        option outbound 'direct-out'

config routing_rule 'bytefcdnrd'
        option label 'bytefcdnrd'
        option enabled '1'
        option mode 'default'
        option source_ip_is_private '0'
        option ip_is_private '0'
        list rule_set 'Direct_bytefcdnrd'
        option rule_set_ip_cidr_match_source '0'
        option outbound 'direct-out'

config dns_rule 'microsoft_dns'
        option label 'microsoft_dns'
        option enabled '0'
        option mode 'default'
        list rule_set 'microsoft'
        option server 'Aliyun'

config dns_rule 'bytefcdnrd_dns'
        option label 'bytefcdnrd_dns'
        option enabled '1'
        option mode 'default'
        list rule_set 'Direct_bytefcdnrd'
        option server 'Aliyun'

config node '2a40d664a091e6e529d9e599d5be478a'
        option label 'HK1-music'
        option type 'vless'
        option address '123.abc.com'
        option port '*****'
        option uuid '******'
        option tls '1'
        option tls_sni 'music.apple.com'
        option tls_reality '1'
        option tls_reality_public_key '***'
        option tls_reality_short_id '59a67d'
        option tls_utls 'random'
        option vless_flow 'xtls-rprx-vision'
        option packet_encoding 'xudp'

config node '777e7f5a3951f34e569c5b7efba2dc38'
        option label 'HK2-icloud'
        option type 'vless'
        option address '123.abc.com'
        option port '*****'
        option uuid '******'
        option tls '1'
        option tls_sni 'icloud.com'
        option tls_reality '1'
        option tls_reality_public_key '***'
        option tls_reality_short_id '3004b85f94adcd'
        option tls_utls 'random'
        option vless_flow 'xtls-rprx-vision'
        option packet_encoding 'xudp'

config ruleset 'Direct_imgur'
        option label 'Direct_imgur'
        option enabled '1'
        option type 'local'
        option format 'source'
        option path '/etc/homeproxy/ruleset/Direct_imgur.json'

config routing_rule 'imgur'
        option label 'imgur'
        option enabled '1'
        option mode 'default'
        option source_ip_is_private '0'
        option ip_is_private '0'
        list rule_set 'Direct_imgur'
        option rule_set_ip_cidr_match_source '0'
        option outbound 'direct-out'

config node 'b8dd2ed517b1235a0862be42878e1df4'
        option label 'JP1-y9i3va91u'
        option type 'vless'
        option address '123.abc.com'
        option port '***'
        option uuid '***'
        option tls '1'
        option tls_sni 'music.apple.com'
        option tls_reality '1'
        option tls_reality_public_key '***'
        option tls_reality_short_id '3459d48b198421'
        option tls_utls 'random'
        option packet_encoding 'xudp'

config node '8cd7fb34d0fe3d22ddd0b85ec7a8fd0e'
        option label 'sg1-506sgcq9'
        option type 'vless'
        option address '123.abc.com'
        option port '***'
        option uuid '***'
        option tls '1'
        option tls_sni 'music.apple.com'
        option tls_reality '1'
        option tls_reality_public_key 'IGjenTQ3uGR0hyWOibrcr-y7O646raQKYu6297JCmzE'
        option tls_reality_short_id 'ae89'
        option tls_utls 'random'
        option packet_encoding 'xudp'

config node 'a71fc30798c7fad53b6d422bbb6c75f7'
        option label 'sg2-krealn8m'
        option type 'vless'
        option address '123.abc.com'
        option port '***'
        option uuid '***'
        option tls '1'
        option tls_sni 'icloud.com'
        option tls_reality '1'
        option tls_reality_public_key 'qaUYkpLgsaef9l6mLIQMJEQlgFiJtnQxbU47fx5RaAU'
        option tls_reality_short_id '0666f1'
        option tls_utls 'random'
        option packet_encoding 'xudp'

config node '1a243571f682e00a32d3c12fb0575a22'
        option label 'PRO 新加坡05 | 4x 原生IP'
        option type 'vmess'
        option address '123.abc.com'
        option port '***'
        option uuid '***'
        option vmess_alterid '0'
        option vmess_encrypt 'auto'
        option tls '0'
        option tls_sni 'sg05.kirino.nbsd.us'
        option packet_encoding 'xudp'

### sing-box configuration

{
        "log": {
                "disabled": false,
                "level": "warn",
                "output": "/var/run/homeproxy/sing-box-c.log",
                "timestamp": true
        },
        "dns": {
                "servers": [
                        {
                                "tag": "default-dns",
                                "address": "114.114.114.114",
                                "detour": "direct-out"
                        },
                        {
                                "tag": "system-dns",
                                "address": "local",
                                "detour": "direct-out"
                        },
                        {
                                "tag": "block-dns",
                                "address": "rcode://name_error"
                        },
                        {
                                "tag": "cfg-Aliyun-dns",
                                "address": "quic://dns.alidns.com",
                                "address_resolver": "default-dns",
                                "detour": "direct-out"
                        },
                        {
                                "tag": "cfg-Google-dns",
                                "address": "https://dns.google/dns-query",
                                "address_resolver": "default-dns",
                                "address_strategy": "ipv4_only",
                                "strategy": "ipv4_only",
                                "detour": "cfg-2a40d664a091e6e529d9e599d5be478a-out",
                                "client_subnet": "****"
                        }
                ],
                "rules": [
                        {
                                "outbound": "any",
                                "server": "default-dns"
                        },
                        {
                                "rule_set": [
                                        "cfg-cnip-rule",
                                        "cfg-cnsite-rule"
                                ],
                                "server": "cfg-Aliyun-dns"
                        },
                        {
                                "ip_version": 4,
                                "rule_set": [
                                        "cfg-openai-rule",
                                        "cfg-tiktok-rule",
                                        "cfg-customsite-rule"
                                ],
                                "server": "cfg-Google-dns"
                        },
                        {
                                "rule_set": [
                                        "cfg-Direct_bytefcdnrd-rule"
                                ],
                                "server": "cfg-Aliyun-dns"
                        }
                ],
                "disable_cache": true,
                "disable_expire": false,
                "independent_cache": false,
                "final": "cfg-Google-dns"
        },
        "inbounds": [
                {
                        "type": "direct",
                        "tag": "dns-in",
                        "listen": "::",
                        "listen_port": 5333
                },
                {
                        "type": "mixed",
                        "tag": "mixed-in",
                        "listen": "::",
                        "listen_port": 5330,
                        "udp_timeout": "300s",
                        "sniff": true,
                        "sniff_override_destination": false,
                        "set_system_proxy": false
                },
                {
                        "type": "redirect",
                        "tag": "redirect-in",
                        "listen": "::",
                        "listen_port": 5331,
                        "sniff": true,
                        "sniff_override_destination": false
                },
                {
                        "type": "tproxy",
                        "tag": "tproxy-in",
                        "listen": "::",
                        "listen_port": 5332,
                        "network": "udp",
                        "udp_timeout": "300s",
                        "sniff": true,
                        "sniff_override_destination": false
                }
        ],
        "outbounds": [
                {
                        "type": "direct",
                        "tag": "direct-out",
                        "routing_mark": 100
                },
                {
                        "type": "block",
                        "tag": "block-out"
                },
                {
                        "type": "dns",
                        "tag": "dns-out"
                },
                {
                        "type": "vless",
                        "tag": "cfg-2a40d664a091e6e529d9e599d5be478a-out",
                        "routing_mark": 100,
                        "server": "***",
                        "server_port": ***,
                        "uuid": "***",
                        "flow": "xtls-rprx-vision",
                        "packet_encoding": "xudp",
                        "tls": {
                                "enabled": true,
                                "server_name": "music.apple.com",
                                "insecure": false,
                                "utls": {
                                        "enabled": true,
                                        "fingerprint": "random"
                                },
                                "reality": {
                                        "enabled": true,
                                        "public_key": "APSc7Y9hj_IQa_C5IBZx3jb2sdZ6kqLWgAXMkC7TrQQ",
                                        "short_id": "59a67d"
                                }
                        }
                },
                {
                        "type": "vless",
                        "tag": "cfg-b8dd2ed517b1235a0862be42878e1df4-out",
                        "routing_mark": 100,
                        "server": "***",
                        "server_port": ***,
                        "uuid": "***",
                        "packet_encoding": "xudp",
                        "tls": {
                                "enabled": true,
                                "server_name": "music.apple.com",
                                "insecure": false,
                                "utls": {
                                        "enabled": true,
                                        "fingerprint": "random"
                                },
                                "reality": {
                                        "enabled": true,
                                        "public_key": "61BXmo7yDm9pNgK0CX0aPpLzHzxtJjEe_zHWEBQHmiU",
                                        "short_id": "3459d48b198421"
                                }
                        }
                }
        ],
        "route": {
                "rules": [
                        {
                                "inbound": "dns-in",
                                "outbound": "dns-out"
                        },
                        {
                                "protocol": "dns",
                                "outbound": "dns-out"
                        },
                        {
                                "rule_set": [
                                        "cfg-cnip-rule",
                                        "cfg-cnsite-rule"
                                ],
                                "outbound": "direct-out"
                        },
                        {
                                "ip_version": 4,
                                "rule_set": [
                                        "cfg-openai-rule",
                                        "cfg-tiktok-rule",
                                        "cfg-customsite-rule"
                                ],
                                "outbound": "cfg-b8dd2ed517b1235a0862be42878e1df4-out"
                        },
                        {
                                "rule_set": [
                                        "cfg-pikpak_download-rule"
                                ],
                                "outbound": "direct-out"
                        },
                        {
                                "rule_set": [
                                        "cfg-REJECT_pikpak-rule"
                                ],
                                "outbound": "block-out"
                        },
                        {
                                "rule_set": [
                                        "cfg-Direct_bytefcdnrd-rule"
                                ],
                                "outbound": "direct-out"
                        },
                        {
                                "rule_set": [
                                        "cfg-Direct_imgur-rule"
                                ],
                                "outbound": "direct-out"
                        }
                ],
                "rule_set": [
                        {
                                "type": "remote",
                                "tag": "cfg-cnip-rule",
                                "format": "binary",
                                "url": "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/sing/geo-lite/geoip/cn.srs",
                                "download_detour": "cfg-2a40d664a091e6e529d9e599d5be478a-out"
                        },
                        {
                                "type": "remote",
                                "tag": "cfg-cnsite-rule",
                                "format": "binary",
                                "url": "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/sing/geo-lite/geosite/cn.srs",
                                "download_detour": "cfg-2a40d664a091e6e529d9e599d5be478a-out"
                        },
                        {
                                "type": "remote",
                                "tag": "cfg-openai-rule",
                                "format": "binary",
                                "url": "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/sing/geo-lite/geosite/openai.srs",
                                "download_detour": "cfg-2a40d664a091e6e529d9e599d5be478a-out"
                        },
                        {
                                "type": "remote",
                                "tag": "cfg-tiktok-rule",
                                "format": "binary",
                                "url": "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/sing/geo-lite/geosite/tiktok.srs",
                                "download_detour": "cfg-2a40d664a091e6e529d9e599d5be478a-out"
                        },
                        {
                                "type": "local",
                                "tag": "cfg-customsite-rule",
                                "format": "source",
                                "path": "/etc/homeproxy/ruleset/gemini.json"
                        },
                        {
                                "type": "local",
                                "tag": "cfg-pikpak_download-rule",
                                "format": "source",
                                "path": "/etc/homeproxy/ruleset/pikpak_download.json"
                        },
                        {
                                "type": "local",
                                "tag": "cfg-REJECT_pikpak-rule",
                                "format": "source",
                                "path": "/etc/homeproxy/ruleset/pikpak_REJECT.json"
                        },
                        {
                                "type": "local",
                                "tag": "cfg-Direct_bytefcdnrd-rule",
                                "format": "source",
                                "path": "/etc/homeproxy/ruleset/Direct_bytefcdnrd.json"
                        },
                        {
                                "type": "local",
                                "tag": "cfg-Direct_imgur-rule",
                                "format": "source",
                                "path": "/etc/homeproxy/ruleset/Direct_imgur.json"
                        }
                ],
                "auto_detect_interface": true,
                "final": "cfg-2a40d664a091e6e529d9e599d5be478a-out"
        },
        "experimental": {
                "cache_file": {
                        "enabled": true,
                        "path": "/var/run/homeproxy/cache.db"
                }

### HomeProxy log

2024-11-24 20:10:51 [DAEMON] Reloading service...
2024-11-24 20:10:54 [DAEMON] Service stopped.
2024-11-24 20:10:57 [DAEMON] sing-box 1.10.1 started.

### sing-box log

没有

### OpenWrt/ImmortalWrt release

23.05.4 r28061-399f9a1db3

### Device

Default string Default string

### Additional information

pve下lxc安装的immortalwrt 23.05.4；pve版本：8.3.0

### Terms

- [X] I confirm that the HomeProxy I installed is from official source, like GitHub artifacts or official ImmortalWrt opkg feeds.
- [X] I confirm that the Homeproxy I installed does not contain Clash mode support.
- [X] I confirm that the version of OpenWrt/ImmortalWrt I installed is >= 23.05.
- [X] I confirm that I have installed the latest version of HomeProxy and sing-box.
- [X] I confirm that I have read the sing-box documentation, understand the meaning of all the configuration items I added.
- [X] I confirm that I have not mixed iptables and nftables rules.
- [X] I confirm that I have not modified system DNS settings, or enabled any other DNS servers like MosDNS and SmartDNS.
- [x] I confirm that I have selected all terms **blindly**.

**Comment by 1715173329** [comment]
清除浏览器缓存。
