### ISSUE TITLE
JustMySocks的vmess分享链接无法导入

### ISSUE THREAD

**Issue by MirMyth** [immortalwrt/homeproxy#228]
### Feature description

JustMySocks的vmess分享链接缺少v字段导致root/etc/homeproxy/scripts/update_subscriptions.uc的372行执行后return null，建议去掉if (uri.v != '2')的判断，因为其他软件基本都能成功导入JustMySocks的vmess分享链接

**Comment by 1715173329** [comment]
建议扔掉 JustMySocks，因为其他机场基本都遵守 VMess 分享链接标准，至少不会增减字段。

**Comment by 1715173329** [comment]
开工单让 JMS 遵守标准。
