### ISSUE TITLE
教程

### ISSUE THREAD

**Issue by zjmsjla** [immortalwrt/homeproxy#230]
### Feature description

请问官方版本自定义路由怎么用啊，有没有相关教程，能找到的教程都是不适用官方版本的

**Comment by 1715173329** [comment]
sing-box 的文档怎么写的，就怎么用。

**Comment by nczyw** [comment]
我仓库中有个[HomeProxyConfig](https://github.com/nczyw/HomeProxyConfig)，里面有做好了的配置文件，我是一步一步手搓出来的，配置拿去就可以使用，大部分的含义我都理解了，如有不理解的地方，也可以问我
