### ISSUE TITLE
路由节点名称有误

### ISSUE THREAD

**Issue by zjmsjla** [immortalwrt/homeproxy#233]
### Bug description

路由节点卷标显示不同步。一些日志和配置文件需要晚上才能放上

### Actual behavior

项目具体名称忘了，大概是这样
1、自定义路由模式，在路由节点处输入Direct并点击新建
2、在新建页面将卷标从Direcrt改为Proxy，并完成新建节点配置
3、在规则集处，选择规则集出站为Proxy，保存应用后在外部显示的出站为**Direct**，没有同步节点卷标

### Expected behavior

1、自定义路由模式，在路由节点处输入Direct并点击新建
2、在新建页面将卷标从Direcrt改为Proxy，并完成新建节点配置
3、在规则集处，选择规则集出站为Proxy，保存应用后在外部显示的出站为**Proxy**

### HomeProxy configuration

1

### sing-box configuration

1

### sing-box log

1

### OpenWrt/ImmortalWrt release

23.05

### Device

设备XR30，刷的RAX3000M固件

### Terms

- [X] I confirm that the HomeProxy I installed is from official source, like GitHub artifacts or official ImmortalWrt opkg feeds.
- [X] I confirm that the Homeproxy I installed does not contain Clash mode support.
- [X] I confirm that the version of OpenWrt/ImmortalWrt I installed is >= 23.05.
- [X] I confirm that I have installed the latest version of HomeProxy and sing-box.
- [X] I confirm that I have read the sing-box documentation, understand the meaning of all the configuration items I added.
- [X] I confirm that I have not mixed iptables and nftables rules.
- [X] I confirm that I have not modified system DNS settings, or enabled any other DNS servers like MosDNS and SmartDNS.
- [ ] I confirm that I have selected all terms **blindly**.

**Comment by 1715173329** [comment]
1，有 0 吗？
