### ISSUE TITLE
NaiveProxy 服務端ACME自動簽發憑證失敗

### ISSUE THREAD

**Issue by ctt828** [immortalwrt/homeproxy#237]
### Bug description

- 應是與ujail權限設置問題有關:
`
[FATAL] start service: initialize inbound/naive[cfg-NaiveProxy-in]: create TLS config: x.y.z: obtaining certificate: failed storage check: mkdir /etc/homeproxy: permission denied - storage is probably misconfigured
`

- 實測使用同一份由homeproxy自動產生的sing-box-s.json, 改透過命令行(/usr/bin/sing-box run)執行就可以成功自動簽發憑證並運行服務成功.

- 另外一個情境提供您參考, 例如我若已經使用luci-app-acme處理好了憑證的自動簽發, 我透過luci-app-homeproxy的UI指定已經簽發完成的證書及私鑰檔案(/etc/acme/下面), 這樣也會因為ujail權限問題讀取不到而無法啟動服務.

### HomeProxy configuration

N/A

### sing-box configuration

N/A

### sing-box log

N/A

### OpenWrt/ImmortalWrt release

23.05.4

### Device

x86

### Terms

- [X] I confirm that the HomeProxy I installed is from official source, like GitHub artifacts or official ImmortalWrt opkg feeds.
- [X] I confirm that the Homeproxy I installed does not contain Clash mode support.
- [X] I confirm that the version of OpenWrt/ImmortalWrt I installed is >= 23.05.
- [X] I confirm that I have installed the latest version of HomeProxy and sing-box.
- [X] I confirm that I have read the sing-box documentation, understand the meaning of all the configuration items I added.
- [X] I confirm that I have not mixed iptables and nftables rules.
- [X] I confirm that I have not modified system DNS settings, or enabled any other DNS servers like MosDNS and SmartDNS.
- [ ] I confirm that I have selected all terms **blindly**.

**Comment by 1715173329** [comment]
```patch
diff --git a/root/etc/init.d/homeproxy b/root/etc/init.d/homeproxy
index c035030..ca9e4ec 100755
--- a/root/etc/init.d/homeproxy
+++ b/root/etc/init.d/homeproxy
@@ -167,7 +167,8 @@ start_service() {
 			procd_add_jail "sing-box-c" log procfs
 			procd_add_jail_mount "$RUN_DIR/sing-box-c.json"
 			procd_add_jail_mount_rw "$RUN_DIR/sing-box-c.log"
-			procd_add_jail_mount "$HP_DIR/certs/"
+			procd_add_jail_mount_rw "$HP_DIR/certs/"
+			procd_add_jail_mount "/etc/acme/"
 			procd_add_jail_mount "/etc/ssl/"
 			procd_add_jail_mount "/etc/localtime"
 			procd_add_jail_mount "/etc/TZ"
@@ -254,7 +255,7 @@ start_service() {
 			procd_add_jail "sing-box-s" log procfs
 			procd_add_jail_mount "$RUN_DIR/sing-box-s.json"
 			procd_add_jail_mount_rw "$RUN_DIR/sing-box-s.log"
-			procd_add_jail_mount "$HP_DIR/certs/"
+			procd_add_jail_mount_rw "$HP_DIR/certs/"
 			procd_add_jail_mount "/etc/localtime"
 			procd_add_jail_mount "/etc/TZ"
 			procd_set_param capabilities "/etc/capabilities/homeproxy.json"
@@ -293,6 +294,8 @@ start_service() {
 		echo > "$RUN_DIR/sing-box-s.log"
 		chown sing-box:sing-box "$RUN_DIR/sing-box-s.log"
 		chown sing-box:sing-box "$RUN_DIR/sing-box-s.json"
+		mkdir -p "$HP_DIR/certs"
+		chown sing-box:sing-box "$HP_DIR/certs"
 	fi
 
 	# Setup firewall
```

看一下这样能否工作

**Comment by ctt828** [comment]
- 使用sing-box的acme可以工作了  😄 
- 使用自定義證書跟密鑰路徑還有小問題: 🫤 
1. luci-app-acme產生出來的 private key, 預設權限是600, 所以sing-box in ujail還是讀不了, 我手動改成644就能跑 (順便告知我這一次是用trojan測試, 所以 trojan server 也可以工作)
2. 你這樣改的話等於是有個但書, 而且使用者不清楚: 使用者自定義的證書跟密鑰路徑, 只能放在 /etc/acme, /etc/ssl下, 搭配可任意填值的UI, 有一點缺憾, 不過我也想不到有什麼比較漂亮的解法, 看來ujail帶來了一些額外的維護風險.

**Comment by 1715173329** [comment]
现在会对路径进行 validate。如果 acme 默认 600 权限必须手动修改，那么允许读取大概也没什么意义

**Comment by 1715173329** [comment]
acme 应该利用 hook 将签发的证书复制一份到 homeproxy 的 certs 目录，这样好一点。

**Comment by ctt828** [comment]
我覺得這一條issue可以先關了, title是sing-box acme的問題已解決. 自定義路徑的問題是不是另開一條集思廣益一下? hook的方法有解, 但似乎有點太針對性某種特定的use case.

**Comment by 1715173329** [comment]
hook 应该是很常见的做法，特别是和 web server 一起使用。
自定义路径其实很好办，但没必要。openwrt 升级时默认不会保存那些自定义路径，那么还需要将其写入保留列表。keep it simple and stupid。

**Comment by ctt828** [comment]
同意, 限制自己上傳證書路徑的使用情境, UI也同步有validate就好.
hook的話我的意思是這的確是有效的解法, 只是覺得不必為了這個特定的情境動干戈.

**Comment by ctt828** [comment]
不好意思的借這裡問一下, 我沒有見到homeproxy repo有ipk的releases? 請問有其他地方可以下載的嗎? 另外通常發佈到 ImmortalWrt 預設源週期大概是多長呀? 就是說這兩天的修正我能從哪裡得到ipk手動更新, 或是甚麼時候可以直接在immortalWrt上直接按更新? 謝謝您

**Comment by 1715173329** [comment]
actions 里面有 ci build，immortalwrt 软件源的刷新周期目前比较长，可能要一周左右。

**Comment by ctt828** [comment]
我就是用ci build測試的, 那我就靜等immortalwrt源更新, 謝謝

**Comment by YinsenHo** [comment]
麻烦问下，怎么添加 naiveproxy 的节点呀
