### ISSUE TITLE
更新之后出现bug

### ISSUE THREAD

**Issue by liuzipeng** [immortalwrt/homeproxy#239]
### Bug description

![wechat_2024-12-07_100923_085](https://github.com/user-attachments/assets/d1f0cfd1-8221-4608-91fa-c4a0332ae747)

### HomeProxy configuration

config homeproxy 'infra'
        option __warning 'DO NOT EDIT THIS SECTION, OR YOU ARE ON YOUR OWN!'
        option common_port '22,53,80,143,443,465,853,873,993,995,8080,8443,9418'
        option mixed_port '5330'
        option redirect_port '5331'
        option tproxy_port '5332'
        option dns_port '5333'
        option china_dns_port '5334'
        option tun_name 'singtun0'
        option tun_addr4 '172.19.0.1/30'
        option tun_addr6 'fdfe:dcba:9876::1/126'
        option tun_mtu '9000'
        option tun_gso '0'
        option table_mark '100'
        option self_mark '100'
        option tproxy_mark '101'
        option tun_mark '102'

config homeproxy 'config'
        option main_node '1'
        option main_udp_node 'same'
        option dns_server '1.1.1.1'
        option routing_mode 'bypass_mainland_china'
        option proxy_mode 'redirect_tproxy'
        option ipv6_support '1'
        list china_dns_server '223.5.5.5'

config homeproxy 'control'
        option lan_proxy_mode 'disabled'
        list listen_interfaces 'eth0'
        list wan_direct_ipv4_ips '43.154.241.27'

config homeproxy 'routing'
        option sniff_override '1'
        option default_outbound 'direct-out'
        option udp_timeout '300'
        option bypass_cn_traffic '0'

config homeproxy 'dns'
        option dns_strategy 'prefer_ipv4'
        option default_server 'default-dns'

config homeproxy 'subscription'
        option auto_update '0'
        option allow_insecure '0'
        option packet_encoding 'xudp'
        option update_via_proxy '0'
        option filter_nodes 'blacklist'
        list filter_keywords '重置|到期|过期|剩余|套餐'
        list filter_keywords 'Expiration|Remaining'

config homeproxy 'server'
        option enabled '0'
        option auto_firewall '0'

config dns_rule 'nodes_domain'
        option label 'NodesDomain'
        option enabled '1'
        option mode 'default'
        list outbound 'any-out'
        option server 'default-dns'

### sing-box configuration

root@ImmortalWrt:~# cat /var/run/homeproxy/sing-box-c.json
{
        "log": {
                "disabled": false,
                "level": "warn",
                "output": "/var/run/homeproxy/sing-box-c.log",
                "timestamp": true
        },
        "dns": {
                "servers": [
                        {
                                "tag": "default-dns",
                                "address": "223.5.5.5",
                                "detour": "direct-out"
                        },
                        {
                                "tag": "system-dns",
                                "address": "local",
                                "detour": "direct-out"
                        },
                        {
                                "tag": "block-dns",
                                "address": "rcode://name_error"
                        },
                        {
                                "tag": "main-dns",
                                "address": "tcp://1.1.1.1",
                                "detour": "main-out"
                        }
                ],
                "disable_cache": false,
                "disable_expire": false,
                "independent_cache": false,
                "final": "main-dns"
        },
        "inbounds": [
                {
                        "type": "direct",
                        "tag": "dns-in",
                        "listen": "::",
                        "listen_port": 5333
                },
                {
                        "type": "mixed",
                        "tag": "mixed-in",
                        "listen": "::",
                        "listen_port": 5330,
                        "sniff": true,
                        "sniff_override_destination": true,
                        "set_system_proxy": false
                },
                {
                        "type": "redirect",
                        "tag": "redirect-in",
                        "listen": "::",
                        "listen_port": 5331,
                        "sniff": true,
                        "sniff_override_destination": true
                },
                {
                        "type": "tproxy",
                        "tag": "tproxy-in",
                        "listen": "::",
                        "listen_port": 5332,
                        "network": "udp",
                        "sniff": true,
                        "sniff_override_destination": true
                }
        ],
        "outbounds": [
                {
                        "type": "direct",
                        "tag": "direct-out",
                        "routing_mark": 100
                },
                {
                        "type": "block",
                        "tag": "block-out"
                },
                {
                        "type": "dns",
                        "tag": "dns-out"
                },
                {
                        "type": "shadowsocks",
                        "tag": "main-out",
                        "routing_mark": 100,
                        "server": "x.x.x.x",
                        "server_port": xxx,
                        "password": "xxxxx=",
                        "method": "2022-blake3-chacha20-poly1305",
                        "udp_fragment": true
                }
        ],
        "route": {
                "rules": [
                        {
                                "inbound": "dns-in",
                                "outbound": "dns-out"
                        }
                ],
                "rule_set": [
                ],
                "auto_detect_interface": true,
                "final": "main-out"
        }
}

### sing-box log

none

### OpenWrt/ImmortalWrt release

23.05.4 r28061-399f9a1db3

### Device

QEMU Standard PC (i440FX + PIIX, 1996)

### Terms

- [X] I confirm that the HomeProxy I installed is from official source, like GitHub artifacts or official ImmortalWrt opkg feeds.
- [X] I confirm that the Homeproxy I installed does not contain Clash mode support.
- [X] I confirm that the version of OpenWrt/ImmortalWrt I installed is >= 23.05.
- [X] I confirm that I have installed the latest version of HomeProxy and sing-box.
- [X] I confirm that I have read the sing-box documentation, understand the meaning of all the configuration items I added.
- [X] I confirm that I have not mixed iptables and nftables rules.
- [X] I confirm that I have not modified system DNS settings, or enabled any other DNS servers like MosDNS and SmartDNS.
- [X] I confirm that I have selected all terms **blindly**.

**Comment by liuzipeng** [comment]
TypeError
Class must be a descendent of CBIAbstractValue
  at ClassConstructor.option (http://192.168.1.250/luci-static/resources/form.js?v=git-24.314.43925-4431ab0:73:9)
  at ClassConstructor.render (http://192.168.1.250/luci-static/resources/view/homeproxy/server.js?v=git-24.314.43925-4431ab0:37:54)

**Comment by 1715173329** [comment]
清理浏览器缓存。
