### ISSUE TITLE
节点分组，自动切换功能

### ISSUE THREAD

**Issue by chris6868** [immortalwrt/homeproxy#245]
### Feature description

大佬空了可以加一个多机场节点分组，并且自动切换节点的功能吗，比如有两个机场A和B，两个机场高峰期不一样，有时候A机场快，有时候B机场快，这个时候看奈飞什么的又需要同地区ip，两个机场都有几个美国节点，就想把这几个美国节点分到一个组，然后奈飞都走这个组，自动切换更快的节点，不知道好不好添加，如果不好添加就算了，感谢大佬

### Expected behavior

按照用户设置分组，自动选择分组中最快的节点

### Additional information

感谢大佬

**Comment by 1715173329** [comment]
不支持。
