### ISSUE TITLE
 请求 naiveproxy 支持

### ISSUE THREAD

**Issue by YinsenHo** [immortalwrt/homeproxy#247]
### Feature description

为了用 hy2 和 naiveproxy，从 ssr+到 passwall，简直用吐了，dns 很容易出错，要么提示不安全的连接，要么速度非常慢。不经意间发现了 homeproxy，我靠！惊为天人！
简洁，高效，稳定！
hy2 支持非常好，但是我还有一个 naiveproxy 的节点，没有办法添加，万望作者能够支持 naiveproxy。
不胜感激！

**Comment by muink** [comment]
上游 outbound 不支持 [naive](https://sing-box.sagernet.org/configuration/outbound/naive/)

**Comment by YinsenHo** [comment]
> 上游 outbound 不支持 [naive](https://sing-box.sagernet.org/configuration/outbound/naive/)

能否 配合装 naiveproxy.ipk 呢？homeproxy 只做配置的入口

**Comment by MarksonHon** [comment]
@YinsenHo PR welcome
