### ISSUE TITLE
无法保存应用

### ISSUE THREAD

**Issue by sdhz151** [immortalwrt/homeproxy#249]
### Bug description

路由设置页面(设置好功能或不设置)---->保存并应用（光转圈不生效）

### Actual behavior

路由设置页面(设置好功能或不设置)---->保存并应用（光转圈不生效）

### Expected behavior

路由设置页面(设置好功能或不设置)---->保存并应用（光转圈不生效）

### Steps to reproduce

路由设置页面(设置好功能或不设置)---->保存并应用（光转圈不生效）

### HomeProxy configuration

路由设置页面(设置好功能或不设置)---->保存并应用（光转圈不生效）

### sing-box configuration

路由设置页面(设置好功能或不设置)---->保存并应用（光转圈不生效）

### HomeProxy log

路由设置页面(设置好功能或不设置)---->保存并应用（光转圈不生效）

### sing-box log

路由设置页面(设置好功能或不设置)---->保存并应用（光转圈不生效）

### OpenWrt/ImmortalWrt release

OpenWrt24.10

### Device

x86

### Additional information

路由设置页面(设置好功能或不设置)---->保存并应用（光转圈不生效）

### Terms

- [X] I confirm that the HomeProxy I installed is from official source, like GitHub artifacts or official ImmortalWrt opkg feeds.
- [X] I confirm that the Homeproxy I installed does not contain Clash mode support.
- [X] I confirm that the version of OpenWrt/ImmortalWrt I installed is >= 23.05.
- [X] I confirm that I have installed the latest version of HomeProxy and sing-box.
- [X] I confirm that I have read the sing-box documentation, understand the meaning of all the configuration items I added.
- [X] I confirm that I have not mixed iptables and nftables rules.
- [X] I confirm that I have not modified system DNS settings, or enabled any other DNS servers like MosDNS and SmartDNS.
- [ ] I confirm that I have selected all terms **blindly**.

**Comment by Hallsong** [comment]
升级最新源码后，“保存并应用”还是只转圈不生效。

**Comment by ftkey** [comment]
已知问题持续时间3天.   升级最新源码后，“保存并应用”还是只转圈不生效。
