### ISSUE TITLE
最新im版本24.10中主界面点击保存并应用或保存不生效

### ISSUE THREAD

**Issue by jh0072110** [immortalwrt/homeproxy#251]
### Bug description

RT，点完只转菊花不生效（强制应用亦无反应）

### Actual behavior

同上所示

### HomeProxy configuration

貌似跟配置文件无关，从节点设置页面点应用是可以的（但就没法修改主界面的dns地址等选项了）
![image](https://github.com/user-attachments/assets/4926a68b-26d5-4334-942d-fe46cafdb809)

### sing-box configuration

同上所示

### sing-box log

无

### OpenWrt/ImmortalWrt release

ImmortalWrt openwrt-24.10

### Device

R5S

### Terms

- [X] I confirm that the HomeProxy I installed is from official source, like GitHub artifacts or official ImmortalWrt opkg feeds.
- [X] I confirm that the Homeproxy I installed does not contain Clash mode support.
- [X] I confirm that the version of OpenWrt/ImmortalWrt I installed is >= 23.05.
- [X] I confirm that I have installed the latest version of HomeProxy and sing-box.
- [X] I confirm that I have read the sing-box documentation, understand the meaning of all the configuration items I added.
- [X] I confirm that I have not mixed iptables and nftables rules.
- [X] I confirm that I have not modified system DNS settings, or enabled any other DNS servers like MosDNS and SmartDNS.
- [X] I confirm that I have cleared the browser cache.
- [X] I confirm that I have selected all terms **blindly**.

**Comment by jh0072110** [comment]
当然它带来的一个全新的问题就是…关不掉了（笑哭）……

**Comment by jh0072110** [comment]
> 上游 luci 瞎改导致的，要修改配置/关闭 homeproxy 可以用命令行，或者 系统-启动项-homeproxy-停止、禁用

用ssh简单的关闭重启我可以，但是增减“代理域名列表”之类的我就不知道在配置文件的哪里修改了（狗头

**Comment by VIKINGYFY** [comment]
> 上游 luci 瞎改导致的，要修改配置/关闭 homeproxy 可以用命令行，或者 系统-启动项-homeproxy-停止、禁用

问题是，目前用的插件，仅HP无法保存应用，其他没这个问题

**Comment by 1715173329** [comment]
> I confirm that I have selected all terms **blindly**.
