### ISSUE TITLE
Add listen address to inbound

### ISSUE THREAD

**Issue by Ricky-Hao** [immortalwrt/homeproxy#36]
Hi, could you add listen address config to inbound server?

https://github.com/immortalwrt/homeproxy/blob/a9063bd60be9c3d258787146787b777f0ee89a58/root/etc/homeproxy/scripts/generate_server.uc#L47C7-L47C7

**Comment by 1715173329** [comment]
Why?

**Comment by Ricky-Hao** [comment]
And could you also add `bind_interface` to Client Outbound nodes?
I need to set `bind_interface=br-lan` for my home outbound. Not send internal traffic to default interface (`pppoe-wan`).

**Comment by 1715173329** [comment]
> And could you also add bind_interface to Client Outbound nodes?

use `access control` or `custom routing`
