### ISSUE TITLE
如何配置REALITY的h2？

### ISSUE THREAD

**Issue by WROIATE** [immortalwrt/homeproxy#46]
REALITY是支持h2的，但是在homeproxy里没有看到h2的选项，请问是有什么特殊配法吗

**Comment by 1715173329** [comment]
自己看 sb 文档去。

**Comment by WROIATE** [comment]
> 自己看 sb 文档去。

sb文档在多路复用和v2ray传输层有http2描述，但是没有明确告知h2在sb中已经自适应在http协议中，所以让人比较迷惑

这边在chika0801的仓库下找到一个配置样例，供其他不清楚的人参考
https://github.com/chika0801/sing-box-examples/blob/main/VLESS-H2-uTLS-REALITY/config_client.json
