### ISSUE TITLE
How to create a inbound

### ISSUE THREAD

**Issue by kunger97** [immortalwrt/homeproxy#5]
I try to add a node,then start the server it shows Error: no valid inbound found.

**Comment by 1715173329** [comment]
can u paste the uci/sb config file?

**Comment by kunger97** [comment]
I'm using luci-app to add node. is this the config file?
`config homeproxy 'config'
        option main_udp_server 'same'
        option routing_port 'common'
        option dns_server '8.8.8.8'
        option main_udp_node 'nil'
        option routing_mode 'bypass_mainland_china'
        option main_server 'M247'
        option main_node 'nil'

config homeproxy 'routing'
        option sniff_override '1'
        option default_outbound 'direct-out'
        option default_tun_stack 'gvisor'

config homeproxy 'dns'
        option dns_strategy 'prefer_ipv4'
        option disable_cache '0'
        option disable_cache_expire '0'
        option default_server 'default-dns'

config homeproxy 'subscription'
        option dns_strategy 'prefer_ipv4'
        option default_server 'local-dns'
        option disable_cache '0'
        option disable_cache_expire '0'
        option auto_update '0'
        option update_via_proxy '0'
        option filter_nodes 'disabled'
        option allow_insecure '0'
        option packet_encoding 'xudp'

config homeproxy 'server'
        option enabled '0'
        option auto_firewall '0'`

**Comment by 1715173329** [comment]
i'm sorry that i made a mistake, the correct option is `main_node`, not `main_server`.
will fix it later.

**Comment by 1715173329** [comment]
fixed.
