### ISSUE TITLE
Feature Request: Add Support for SSH Type Outband

### ISSUE THREAD

**Issue by devAlikhani** [immortalwrt/homeproxy#50]
I am writing to request the addition of "ssh" type outband to HomeProxy's existing options, which would significantly enhance its functionality for users in certain regions.

The JSON format for this "ssh" outband would look something like this:

```
{
    "type": "ssh"
    "tag": "ssh-out",
    "server": "server-address",
    "server_port": 2222,
    "user": "ed353c36-57dc-4f0c-b545-229cbb0c4b81",
    "private_key": "-----BEGIN OPENSSH PRIVATE KEY-----\n[...]\n-----END OPENSSH PRIVATE KEY-----\n",
    "host_key": [
        "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBmeOGQXgbEwO4EMt+IW6OFiXnFugh8KBq3uYY5OqBGO",
        "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFTyzHf6aGR+GXPphhMhtshK/YN1kzhFrZbQa/HIQH5/QUXbUq+MHZ5nRN/Ej5o5XLchWQIDvnb77omOOpCx004="
    ]
}
```

I know this method is entirely custom and does not have standard share links, but it would be great if users could select and add these custom fields through the LuCI UI.

I live not in Mainland China but in Iran. In our country, this method of connection is very stable and secure. Adding this feature would greatly benefit users in regions with similar network constraints.

Thank you for considering this feature request. Your work on HomeProxy is greatly appreciated, and this addition would make it even more valuable for users like me.

**Comment by 1715173329** [comment]
Planned.

**Comment by 1715173329** [comment]
done in c6963de9b1161bddece6770dc13ec4bcf7d36008
