### ISSUE TITLE
修改访问控制下域名代理列表提示没有待应用的更改

### ISSUE THREAD

**Issue by StarryskyLL** [immortalwrt/homeproxy#53]
![QQ截图20231212103857](https://github.com/immortalwrt/homeproxy/assets/43089412/2997c57b-43c2-442e-8084-622e08920dde)
修改`访问控制`下的`代理域名列表`和`直连域名列表`的内容点击`保存并应用`提示`没有待应用的更改`
需要手动切换节点或者修改其他设置才能`保存并应用`让域名列表生效

**Comment by 1715173329** [comment]
因为这不是 uci 配置，需要手动重启服务。
