### ISSUE TITLE
大屌，机场订阅好像拉不出来～

### ISSUE THREAD

**Issue by Alexrobot03** [immortalwrt/homeproxy#6]

**Comment by 1715173329** [comment]
什么都发了，废话一堆就是不发日志。你不如去街上请个算命先生帮你算算。

**Comment by Alexrobot03** [comment]
**不好意思，网络延迟略大，才收到消息，一会瞧瞧日志应该在哪个位置看，感谢回复～**> 什么都发了，废话一堆就是不发日志。你不如去街上请个算命先生帮你算算。
