### ISSUE TITLE
无法使用wireguard节点，日记显示 [31mFATAL[0m[0000] parse outbound[3]: create WireGuard device: numerical result out of range

### ISSUE THREAD

**Issue by Xymmh** [immortalwrt/homeproxy#64]
<img width="576" alt="image" src="https://github.com/immortalwrt/homeproxy/assets/45114927/4c7f93e9-2d0f-443c-977f-a734ad868445">

尝试修改过配置文件的各项参数，均不能解决问题

系统版本：ImmortalWrt 23.05.1 r27304-31bc47589e / LuCI openwrt-23.05 branch git-23.354.11083-b1b77b6
homeproxy版本：git-23.356.21884-c03d6fb

**Comment by 1715173329** [comment]
please paste your final client configuration here, remember to remove your private info

**Comment by jefison** [comment]
我的docker 版容器 immortalwrt 增加warp team 的wireguard 配置时，报以上错误。
以下是 /var/run/homeproxy/sing-box-c.json中相关配置
{
                        "type": "wireguard",
                        "tag": "main-out",
                        "routing_mark": 100,
                        "server": "162.159.192.241",
                        "server_port": 8854,
                        "private_key": "mJRBJt2cfQRc82cFqQr1TNExioxylg=",
                        "system_interface": true,
                        "interface_name": "wg-warp_team-out",
                        "local_address": [
                                "172.16.0.2/32",
                                "2606:4700:110:832f:d522:970:2956/128"
                        ],
                        "peer_public_key": "bmXOC+F1FxEMF9dyizHwPfgyo=",
                        "reserved": [
                                31,
                                36,
                                228
                        ],
                        "mtu": 1280
                }

**Comment by jefison** [comment]
> 我的docker 版容器 immortalwrt 增加warp team 的wireguard 配置时，报以上错误。 以下是 /var/run/homeproxy/sing-box-c.json中相关配置
> 
> ```json
> {
>                         "type": "wireguard",
>                         "tag": "main-out",
>                         "routing_mark": 100,
>                         "server": "<truncated>",
>                         "server_port": <truncated>,
>                         "private_key": "<truncated>",
>                         "system_interface": true,
>                         "interface_name": "wg-warp_team-out",
>                         "local_address": [
>                                 "172.16.0.2/32",
>                                 "<truncated>"
>                         ],
>                         "peer_public_key": "<truncated>",
>                         "reserved": [
>                                 31,
>                                 36,
>                                 228
>                         ],
>                         "mtu": 1280
>                 }
> ```
升级到sing-box内核后问题解决。

**Comment by Xymmh** [comment]
是tag的问题，tag里面不能有符号
