### ISSUE TITLE
关于DNS设置的疑问

### ISSUE THREAD

**Issue by junjun1121** [immortalwrt/homeproxy#66]
先说Sorry因为我觉得应该是开在Discuss里的但天灵大佬没有开…
主要是有些许疑惑，刚开始尝试使用
请教一下，如果路由开启mosdns的情况下，
DNS 服务器/国内 DNS 服务器 应该选择【禁用】还是选择【使用 WAN 下发的 DNS】才会把解析权交给mosdns使用呢？
还是说……都不会？

**Comment by muink** [comment]
都不会, 需要在`DNS 服务器`指定mosdns的监听地址和端口

**Comment by jh0072110** [comment]
> 都不会, 需要在`DNS 服务器`指定mosdns的监听地址和端口

端口该如何指定，输入:或者#都会被标红唉

**Comment by muink** [comment]
好像是的, 只允許輸入ip 😿

**Comment by shiyu1314** [comment]
> > 都不会, 需要在`DNS 服务器`指定mosdns的监听地址和端口
> 
> 端口该如何指定，输入:或者#都会被标红唉

直接mosdns dns转发打开
HomeProxy 国内外dns指向本地127.0.0.1

**Comment by jh0072110** [comment]
> > > 都不会, 需要在`DNS 服务器`指定mosdns的监听地址和端口
> > 
> > 
> > 端口该如何指定，输入:或者#都会被标红唉
> 
> 直接mosdns dns转发打开 HomeProxy 国内外dns指向本地127.0.0.1

这不太合理吧，不指端口是不是有点愣来了…

**Comment by shiyu1314** [comment]
> > > > 都不会, 需要在`DNS 服务器`指定mosdns的监听地址和端口
> > > 
> > > 
> > > 端口该如何指定，输入:或者#都会被标红唉
> > 
> > 直接mosdns dns转发打开 HomeProxy 国内外dns指向本地127.0.0.1
> 
> 这不太合理吧，不指端口是不是有点愣来了…

dnsmasq都转发到mosdns了 怎么不合理

**Comment by 1715173329** [comment]
全局模式、自定义模式，HP 会接管所有 DNS 请求。
GFWList 模式，HP 只接管 GFWList 内域名 DNS 请求。
绕过大陆模式，HP 只接管 GFWList 内域名 DNS 请求；开启国内 DNS 后，接管所有 DNS 请求。
代理大陆模式，HP 只接管 ChinaList 内域名 DNS 请求。

sing-box 的文档未声明支持非标准端口，所以 HP 不会支持。
HP 也不会考虑支持 MosDNS 等其他 DNS 服务，折腾 DNS 没有任何意义。

**Comment by 1715173329** [comment]
Moved to discussion.
