### ISSUE TITLE
弱弱的问一下，hp会更新rule-set

### ISSUE THREAD

**Issue by elric8** [immortalwrt/homeproxy#71]
两个问题
1，因为家里的路由器，怕更新了，sing-box1.8+ geosite移除了，还要重新配置
2，hp的配置文件支持手搓不，像配置rule-set，不能手搓有点麻烦
感谢大佬

**Comment by muink** [comment]
SB 有缺省的GEO二进制规则, 可以直接用: [sing-geoip](https://github.com/SagerNet/sing-geoip), [sing-geosite](https://github.com/SagerNet/sing-geosite)
同样也可以手搓配置: https://sing-box.sagernet.org/configuration/rule-set/source-format
另外手搓的配置也支持使用 `sing-box rule-set compile` 命令转换为体积更小的二进制文件
