### ISSUE TITLE
Enhancement: specify chnlist-file for chinadns-ng

### ISSUE THREAD

**Issue by ShadowOfTheDay** [immortalwrt/homeproxy#77]
Currently, only the `gfwlist-file` is specified for chinadns-ng, but not the `chnlist-file`. This may cause suboptimal DNS resolution for some websites. For example:

- Current behavior: since `google.com` is in `gfwlist-file`, `dl.google.com` is resolved by trust-dns with proxy to a foreign IP address.
- After specifying `chnlist-file`: since `dl.google.com` is in `chnlist-file`, `dl.google.com` is resolved by a DNS server in China to a China IP address.

**Comment by 1715173329** [comment]
Sounds good.
