### ISSUE TITLE
命中 Direct 的流量 NAT 类型改变

### ISSUE THREAD

**Issue by muink** [immortalwrt/homeproxy#95]
## 问题发现
因为一直都是在路由器上用 natmap 打洞, 通过打洞出来的 tcp/udp 端口连回家里或访问开放的服务
最近一次远程回家, 要测试点东西. 就把 homeproxy 的 `Bypass CN traffic` 给关了. 结果远程连接直接就断了, 其他的服务也都挂了

## 初步检查
回家后检查是 keep-alive 服务器命中了 Direct 规则, (natmap 定期向 `www.baidu.com` 发送 HTTP keep-alive 报文来保活)
之前因为开启了 `Bypass CN traffic` 流量直接在防火墙就走直连了, 没有再走一次 sing-box, 打洞就成功了
仔细检查后发现只要是命中 Direct 规则的流量, 全部变成了 `端口过滤型 NAT`, 也难怪打洞会失败了

## 检查结果
这是没有开启 homeproxy 时候的 tcp/udp 检查结果
![Snipaste_2024-04-13_20-01-30](https://github.com/immortalwrt/homeproxy/assets/7929014/3c4ec076-2f07-405d-8b5e-c155dd8ae013)

这是开启 homeproxy 时候的 tcp/udp 检查结果
查了下这个文章[STUN (RFC 3489) vs. STUN (RFC 5389/5780)](https://netmanias.com/en/post/techdocs/6065/nat-network-protocol/stun-rfc-3489-vs-stun-rfc-5389-5780)
出站的 srcnat 应该正常的, 但入站的就被过滤掉了
![Snipaste_2024-04-13_19-59-05](https://github.com/immortalwrt/homeproxy/assets/7929014/d79cf614-8b84-4256-829e-cc4ebe0ad3cd)

**Comment by muink** [comment]
似乎与 openclash 的问题很像 https://github.com/vernesong/OpenClash/issues/2288

**Comment by muink** [comment]
查出原因了 本机端口 3456 在经过 sing-box 后转换为了 ip_local_port_range 的 port, 绕过了 3456 的 input 规则, 但是网关又不是 Full cone NAT, 自然连接降级了

**Comment by uply23333** [comment]
大佬 这个问题有办法解决吗？

**Comment by uply23333** [comment]
问题已解决，我的方法是在 nftable 中过滤了 natmap 的本地源端口。

我的代理模式是：Redirect TCP + TProxy UDP

因为我是 tcp 打洞，所以需要改 tcp劫持规则。

## 修改防火墙规则
路径： `/etc/homeproxy/scripts/firewall_post.ut`
添加：
在 `homeproxy_redirect_proxy_port` 中添加 `tcp sport { 12345, 12346 } counter return`

![Image](https://github.com/user-attachments/assets/4d4480df-6c47-4d7e-be9c-a6ee1c95b383)

**Comment by muink** [comment]
@uply23333 我用 natmap 自带的 fwmark 打标功能打上 100, 自动绕防火墙了
