### ISSUE TITLE
一个小Bug

### ISSUE THREAD

**Issue by jh0072110** [immortalwrt/homeproxy#99]
点击更新大陆域名列表版本时，即使已经是最新版依旧会显示更新成功。
![image](https://github.com/immortalwrt/homeproxy/assets/50496854/79350db6-4e73-41bf-a3ed-5061c9d9b285)

**Comment by ximiTech** [comment]
感觉这个bug 藏得很深。。。

**Comment by jh0072110** [comment]
> 感觉这个bug 藏得很深。。。

要不是连点了两次谁能发现呢……

**Comment by muink** [comment]
https://github.com/immortalwrt/homeproxy/blob/master/root/etc/homeproxy/scripts/update_resources.sh#L99
这段代码覆写了前面的 exit code
